#!/usr/bin/env python3
"""Generate the pokeemerald overworld sprites of RFVF+ (the OBJ_EVENT_GFX_HOENN_* graphics ids) from pret/pokeemerald.

Usage (Git Bash, from the repo root), then build as usual:
    uv run --no-project --with pillow python tools/hoenn_import/hoenn_sprites.py [--emerald ../pokeemerald] [--check]
    --check: write nothing, exit 1 if a generated file would change (re-running with the same pokeemerald changes
    nothing).

Every Emerald object graphic is imported but those skipped() leaves out (player avatar states, link avatars, berry
trees, secret base decorations): OBJ_EVENT_GFX_HOENN_X shows Emerald's OBJ_EVENT_GFX_X with Emerald's pixels, palettes,
frames and animations. Hoenn layouts load Emerald's NPC palettes (InitObjectEventPalettes(OBJ_PAL_MODE_HOENN)), so a Hoenn
map uses these ids (hoenn_import.py maps Emerald objects to them) and a Kanto map never does (--check-gfx).

GRAPHICS IDS ARE STORED IN SAVES: the OBJ_EVENT_GFX_HOENN_ ids already defined keep their numbers; the missing ones are
appended after the highest one, in Emerald id order, inside the Hoenn block (256-511). Never renumber or remove one.

Written between "BEGIN/END generated by tools/hoenn_import/hoenn_sprites.py: <block>" comment lines (the rest of
each file is left alone; Porymap reads these files, so the blocks follow the surrounding patterns):
  include/constants/event_objects.h             ids, NUM_OBJ_EVENT_GFX
  src/data/object_events/object_event_graphics.h  INCBINs: graphics/object_events/pics/hoenn/**, palettes/hoenn_*
  src/data/object_events/object_event_pic_tables.h, object_event_anims.h (+ sStepAnimTables),
      object_event_graphics_info.h, object_event_graphics_info_pointers.h (declarations, pointers, variants)
  src/event_object_movement.c                   palette tags, sObjectEventSpritePalettes, reflection palette sets
  src/dynamic_placeholder_text_util.c           text colors of the Hoenn ids
  spritesheet_rules.mk                          4bpp rules (Emerald's own rule of each sheet, if it has one)
  graphics/object_events/pics/hoenn/**.png, graphics/object_events/palettes/hoenn_*.pal: copies of Emerald's files
    (pics/<category>/<path> -> pics/hoenn/<path>, palettes/<name>.pal -> palettes/hoenn_<name>.pal)

How each part is ported:
  - graphics info: field by field; paletteSlot is the same slot (same enum, Hoenn maps load Emerald's palettes there);
    paletteTag NPC_N -> HOENN_NPC_N, a special palette X -> HOENN_X (+ its reflections, gSpecialObjectReflection-
    PaletteSets); reflectionPaletteTag -> this repo's tag of the same name (checked: same palette).
  - pic tables: Emerald's frames in Emerald's order. When the anim table used here shows a later frame, copies of
    frame 0 follow, so no frame past the table is ever read (this repo's sAnimTable_Standard has ANIM_RAISE_HAND,
    FRLG's VS Seeker, on frame 9; Emerald walkers have frames 0-8).
  - anim tables: this repo's table when it plays the same anims at every Emerald index and has the same
    sStepAnimTables entry (it may have more anims), else Emerald's, as sAnimTable_HoennX with its sAnim_HoennY (an
    anim this repo has with the same name and commands is shared). Subsprite tables and base OAMs: this repo's
    (checked equal to Emerald's).
  - text colors: pokeemerald has no NPC text color table (it prints every NPC in the same colors). FRLG's rule by
    Emerald's own graphics folder: pokemon/ -> MON, misc/ -> NEUTRAL, people/ -> FEMALE (FEMALE below) or MALE.
  - VARIANTS: sHoennVariantGraphicsInfoPointers, the sprite a Hoenn map shows for a Kanto id (safety net only).
"""
import argparse
import re
import shutil
import sys
from pathlib import Path

from PIL import Image

REPO = Path(__file__).resolve().parents[2]
TOOL = "generated by tools/hoenn_import/hoenn_sprites.py"
OBJ = "src/data/object_events/"
PICS = "graphics/object_events/pics/"
PALS = "graphics/object_events/palettes/"
HOENN_IDS = range(256, 512)  # event_objects.h: HOENN_OBJ_EVENT_GFX_BASE; the next region starts at 512
FIRST_PAL_TAG = 0x1125  # first free tag after this repo's OBJ_EVENT_PAL_TAG_LADY (src/event_object_movement.c)
INFO_FIELDS = ["tileTag", "paletteTag", "reflectionPaletteTag", "size", "width", "height", "paletteSlot",
               "shadowSize", "inanimate", "disableReflectionPaletteLoad", "tracks", "oam", "subspriteTables",
               "anims", "images", "affineAnims"]


def skipped(name):
    """Emerald gfx not imported: the player is Red/Leaf, link partners are drawn by FRLG's own code, FRLG has no
    berry trees nor secret bases."""
    return bool(re.fullmatch(r"(BRENDAN|MAY)_(NORMAL|MACH_BIKE|ACRO_BIKE|SURFING|FIELD_MOVE|UNDERWATER|FISHING|"
                             r"WATERING|DECORATING)|LINK_(RS_)?(BRENDAN|MAY)|RED|LEAF|BERRY_TREE\w*|\w+_(DOLL|CUSHION)",
                             name))


# people/ sprites of a woman or a girl (red text); every other people/ sprite is MALE
FEMALE = {
    "TWIN", "GIRL_1", "GIRL_2", "LITTLE_GIRL", "GIRL_3", "WOMAN_1", "POKEFAN_F", "WOMAN_2", "EXPERT_F", "WOMAN_3",
    "WOMAN_4", "LINK_RECEPTIONIST", "OLD_WOMAN", "PICNICKER", "WOMAN_5", "HEX_MANIAC", "SWIMMER_F", "BEAUTY", "LASS",
    "RUNNING_TRIATHLETE_F", "TUBER_F", "CYCLING_TRIATHLETE_F", "NURSE", "REPORTER_F", "ANABEL", "GRETA", "LUCY",
    "ROOFTOP_SALE_WOMAN", "TEALA", "RIVAL_MAY_NORMAL", "RIVAL_MAY_MACH_BIKE", "RIVAL_MAY_ACRO_BIKE",
    "RIVAL_MAY_SURFING", "RIVAL_MAY_FIELD_MOVE", "AQUA_MEMBER_F", "MAGMA_MEMBER_F", "PHOEBE", "GLACIA", "ROXANNE",
    "FLANNERY", "WINONA", "LIZA", "HOT_SPRINGS_OLD_WOMAN", "MOM", "UNION_ROOM_NURSE",
}
COLOR_BY_FOLDER = {"pokemon": "NPC_TEXT_COLOR_MON", "misc": "NPC_TEXT_COLOR_NEUTRAL"}

# Kanto id -> Emerald gfx of the same character class, both sheets looked at side by side (same gender; a named
# character only with itself). Only ids drawn with an NPC palette slot need one: a Hoenn map loads Emerald's palettes
# there. "class:" = the sprite pokeemerald's own trainers of that class use (Emerald map data).
VARIANTS = {
    "LITTLE_BOY": "LITTLE_BOY", "LITTLE_GIRL": "LITTLE_GIRL", "YOUNGSTER": "YOUNGSTER", "BUG_CATCHER": "BUG_CATCHER",
    "LASS": "LASS", "WOMAN_1": "WOMAN_1", "FAT_MAN": "FAT_MAN", "WOMAN_2": "WOMAN_2", "BEAUTY": "BEAUTY",
    "WOMAN_3": "WOMAN_3", "OLD_MAN_1": "OLD_MAN", "OLD_MAN_2": "OLD_MAN", "OLD_WOMAN": "OLD_WOMAN",
    "TUBER_M_WATER": "TUBER_M_SWIMMING", "TUBER_F": "TUBER_F", "TUBER_M_LAND": "TUBER_M", "CAMPER": "CAMPER",
    "PICNICKER": "PICNICKER", "SWIMMER_M_WATER": "SWIMMER_M", "SWIMMER_F_WATER": "SWIMMER_F",
    "SWIMMER_F_WATER_2": "SWIMMER_F", "GBA_KID": "GAMEBOY_KID", "BLACKBELT": "BLACK_BELT", "SCIENTIST": "SCIENTIST_1",
    "HIKER": "HIKER", "FISHER": "FISHERMAN", "CHEF": "COOK", "GENTLEMAN": "GENTLEMAN", "SAILOR": "SAILOR",
    "NURSE": "NURSE", "CABLE_CLUB_RECEPTIONIST": "TEALA", "UNION_ROOM_RECEPTIONIST": "LINK_RECEPTIONIST",
    "CLERK": "MART_EMPLOYEE", "MG_DELIVERYMAN": "MYSTERY_GIFT_MAN", "POKE_MANIAC": "MANIAC", "PSYCHIC_M": "PSYCHIC_M",
    "TWIN": "TWIN", "SCOTT": "SCOTT", "EM_BRENDAN": "RIVAL_BRENDAN_NORMAL", "EM_MAY": "RIVAL_MAY_NORMAL",
    "ANABEL": "ANABEL", "TUCKER": "TUCKER", "GRETA": "GRETA", "SPENSER": "SPENSER", "NOLAND": "NOLAND",
    "LUCY": "LUCY", "BRANDON": "BRANDON",
    "ITEM_BALL": "ITEM_BALL", "CUT_TREE": "CUTTABLE_TREE", "ROCK_SMASH_ROCK": "BREAKABLE_ROCK",
    "PUSHABLE_BOULDER": "PUSHABLE_BOULDER", "FOSSIL": "FOSSIL",
    "PIKACHU": "PIKACHU", "MEW": "MEW", "LUGIA": "LUGIA", "HO_OH": "HOOH", "DEOXYS_N": "DEOXYS", "LATIAS": "LATIAS",
    "LATIOS": "LATIOS", "SUDOWOODO": "SUDOWOODO",
    # class:
    "COOLTRAINER_M": "MAN_3", "COOLTRAINER_F": "WOMAN_5", "BATTLE_GIRL": "GIRL_3", "BIRD_KEEPER": "MAN_5",
    "AROMA_LADY": "WOMAN_2", "POKEMON_BREEDER": "WOMAN_2", "POKEMON_RANGER_M": "CAMPER",
    "POKEMON_RANGER_F": "PICNICKER", "PSYCHIC_F": "LASS", "RUIN_MANIAC": "HIKER", "YOUNG_COUPLE_M": "MAN_4",
    "YOUNG_COUPLE_F": "WOMAN_4",
    # FRLG-Plus master trainers: their class
    "MASTER_BEAUTY": "BEAUTY", "MASTER_BIRD_KEEPER": "MAN_5", "MASTER_BLACK_BELT": "BLACK_BELT",
    "MASTER_BUG_CATCHER": "BUG_CATCHER", "MASTER_COOLTRAINER_M": "MAN_3", "MASTER_HIKER": "HIKER",
    "MASTER_LASS": "LASS", "MASTER_PSYCHIC_M": "PSYCHIC_M", "MASTER_SCIENTIST": "SCIENTIST_1",
    "MASTER_YOUNGSTER": "YOUNGSTER",
}


# ---------------------------------------------------------------- C parsing

def read(path):
    with open(path, encoding="utf-8", newline="") as f:
        return f.read()


def uncomment(text):
    return re.sub(r"//[^\n]*|/\*.*?\*/", "", text, flags=re.S)


def definitions(text, ctype):
    """{name: (full definition text, body)} of every `[static ]const <ctype> name[] = {...};` of `text`."""
    out = {}
    for m in re.finditer(r"^(?:static )?const %s\s*(\w+)\[\w*\]\s*=\s*\{" % ctype, text, re.M):
        i, depth = m.end(), 1
        while depth:
            depth += {"{": 1, "}": -1}.get(text[i], 0)
            i += 1
        assert text[i] == ";", m.group(1)
        out[m.group(1)] = (text[m.start():i + 1], text[m.end():i - 1])
    return out


def defines(*texts):
    """Evaluator of the #define constants of `texts` (enough for anim indices and gfx ids)."""
    raw = {}
    for text in texts:
        raw.update(re.findall(r"^#define[ \t]+(\w+)[ \t]+([^\n]+)", uncomment(text), re.M))

    def ev(expr):
        expr = expr.strip()
        if re.fullmatch(r"\w+", expr) and not expr[0].isdigit():
            return ev(raw[expr])
        return eval(re.sub(r"\b[A-Za-z_]\w*\b", lambda m: str(ev(m.group(0))), expr).replace("/", "//"))
    return ev


def cmds(body):
    """Normalized anim commands of an AnimCmd / AffineAnimCmd array body."""
    out = []
    for name, args in re.findall(r"\b((?:AFFINE)?ANIMCMD_\w+)(?:\(([^)]*)\))?", uncomment(body)):
        vals = []
        for a in (a.strip() for a in args.split(",") if a.strip()):
            key, _, val = a.rpartition("=")
            val = val.strip()
            vals.append((key.strip(), int(val, 0) if re.fullmatch(r"-?(0x[0-9a-fA-F]+|\d+)", val) else val))
        out.append((name, tuple(vals)))
    return out


def anim_tables(text, ev, kind):
    """{table: [anim name by index]} of the `<kind> *const` tables (designated or positional entries)."""
    out = {}
    for name, (_, body) in definitions(text, r"union %s \*const" % kind).items():
        entries, i = {}, 0
        for item in (x.strip() for x in uncomment(body).split(",") if x.strip()):
            m = re.fullmatch(r"\[(.+?)\]\s*=\s*(\w+)", item)
            try:
                i = ev(m.group(1)) if m else i
            except KeyError:  # berry tree stages: not needed
                break
            entries[i] = m.group(2) if m else item
            i += 1
        else:
            out[name] = [entries.get(k) for k in range(max(entries) + 1)]
    return out


def step_tables(text):
    return dict(re.findall(r"\.anims = (\w+),\s*\.animPos = (\{[^}]*\})", text))


def handwritten(text):
    """`text` without the blocks this tool generates (its own output is not "this repo's" data)."""
    return re.sub(r"^[ \t]*(//|#) BEGIN %s: ([^\n]*)\n.*?^[ \t]*\1 END %s: \2\n" % (re.escape(TOOL), re.escape(TOOL)),
                  "", text, flags=re.S | re.M)


class Tree:
    """Object event data of a pokeemerald / pokefirered tree (this repo: hand-written parts only, ids aside)."""

    def __init__(self, root):
        self.root = root
        d = lambda name: handwritten(read(root / OBJ / name))
        self.ids_text = read(root / "include/constants/event_objects.h")
        self.ev = defines(read(root / "include/constants/event_object_movement.h"), self.ids_text)
        ptrs = d("object_event_graphics_info_pointers.h")
        self.pointers = dict(re.findall(r"\[(OBJ_EVENT_GFX_\w+)\]\s*=\s*&(\w+)",
                                        ptrs.split("sHoennVariantGraphicsInfoPointers")[0]))
        self.infos = {n: dict(re.findall(r"\.(\w+)\s*=\s*([^,\n]+),", b)) for n, b in re.findall(
            r"const struct ObjectEventGraphicsInfo (\w+) = \{(.*?)\};", uncomment(d("object_event_graphics_info.h")), re.S)}
        self.pic_tables = {n: re.findall(r"\b(overworld_frame|obj_frame_tiles)\(([^)]*)\)", b)
                           for n, (_, b) in definitions(d("object_event_pic_tables.h"), "struct SpriteFrameImage").items()}
        self.incbins = dict(re.findall(r"const u(?:16|32) (\w+)\[\w*\] = INCBIN_U(?:16|32)\(\"([^\"]+)\"\);",
                                       d("object_event_graphics.h")))
        anims = d("object_event_anims.h")
        self.anim_text = anims
        self.anims = {n: cmds(b) for n, (_, b) in definitions(anims, "union AnimCmd").items()}
        self.affine_anims = {n: cmds(b) for n, (_, b) in definitions(anims, "union AffineAnimCmd").items()}
        self.anim_tables = anim_tables(anims, self.ev, "AnimCmd")
        self.affine_tables = anim_tables(anims, self.ev, "AffineAnimCmd")
        self.steps = step_tables(anims)
        sub = uncomment(d("object_event_subsprites.h"))
        arrays = {n: re.findall(r"\{([^{}]*)\}", b) for n, (_, b) in definitions(sub, "struct Subsprite").items()}
        norm = lambda e: sorted(re.sub(r"\s+", "", f) for f in e.split(",") if f.strip())
        self.subsprites = {}
        for n, (_, b) in definitions(sub, "struct SubspriteTable").items():
            rows = []
            for row in re.findall(r"\{([^{}]*)\}", b):
                parts = [p.strip() for p in row.split(",") if p.strip()] or ["0", "NULL"]
                rows.append(None if parts[1] == "NULL" else [norm(e) for e in arrays[parts[1]]])
            self.subsprites[n] = rows
        self.oams = {n: sorted(re.sub(r"\s+", "", f) for f in b.split(",") if f.strip()) for n, b in re.findall(
            r"const struct OamData (\w+) = \{(.*?)\};", uncomment(d("base_oam.h")), re.S)}


# ---------------------------------------------------------------- generation

def camel(name):  # OBJ_EVENT_PAL_TAG_QUINTY_PLUMP_REFLECTION suffix -> QuintyPlumpReflection
    return "".join(w.capitalize() for w in name.lower().split("_"))


def hoenn(symbol):  # sPicTable_Twin -> sPicTable_HoennTwin
    prefix, _, rest = symbol.partition("_")
    return "%s_Hoenn%s" % (prefix, rest)


class Generator:
    def __init__(self, em):
        self.em, self.fr = Tree(em), Tree(REPO)
        em_mov = read(em / "src/event_object_movement.c")
        self.em_pal_tags = {n: int(v, 16) for n, v in re.findall(r"#define (OBJ_EVENT_PAL_TAG_\w+)\s+(0x[0-9A-Fa-f]+)", em_mov)}
        self.em_palettes = {t: s for s, t in re.findall(r"\{(gObjectEventPal_\w+),\s*(OBJ_EVENT_PAL_TAG_\w+)\}", em_mov)}
        refl_arrays = {n: re.findall(r"OBJ_EVENT_PAL_TAG_\w+", b) for n, (_, b) in definitions(em_mov, r"u16").items()}
        sets = definitions(em_mov, "struct PairedPalettes")["sSpecialObjectReflectionPaletteSets"][1]
        self.em_reflections = {t: refl_arrays[a] for t, a in re.findall(r"\{(OBJ_EVENT_PAL_TAG_\w+),\s*(\w+)\}", sets)
                               if a != "NULL"}
        self.em_rules = dict(re.findall(r"^\$\(OBJEVENTGFXDIR\)/(\S+)\.4bpp: %\.4bpp: %\.png\n\t\$\(GFX\) \$< \$@ ([^\n]*)",
                                        read(em / "spritesheet_rules.mk"), re.M))
        em_ids = {n: int(v) for n, v in re.findall(r"^#define OBJ_EVENT_GFX_(\w+)\s+(\d+)\s*$", self.em.ids_text, re.M)}
        self.scope = [g for g in sorted(em_ids, key=em_ids.get) if not skipped(g)]
        self.ids = self.assign_ids()

    def assign_ids(self):
        define = r"^[ \t]*#[ \t]*define[ \t]+OBJ_EVENT_GFX_HOENN_"
        found = re.findall(define + r"(\w+)[ \t]+(\d+)\b", self.fr.ids_text, re.M)
        ids = {n: int(v) for n, v in found}
        # an id read wrong would be appended again under a new number: stop instead (saves store the numbers)
        assert len(ids) == len(found) == len(re.findall(define, self.fr.ids_text, re.M)), \
            "an OBJ_EVENT_GFX_HOENN_ define is not '#define OBJ_EVENT_GFX_HOENN_X <decimal>', or is defined twice"
        assert sorted(ids.values()) == list(range(HOENN_IDS.start, HOENN_IDS.start + len(ids))), \
            "OBJ_EVENT_GFX_HOENN_ ids are not %d.. without gaps: a number was edited or removed" % HOENN_IDS.start
        assert set(ids) <= set(self.scope), "ids of gfx no longer imported: %s" % sorted(set(ids) - set(self.scope))
        for g in self.scope:
            if g not in ids:
                ids[g] = max(ids.values(), default=HOENN_IDS.start - 1) + 1
        assert all(i in HOENN_IDS for i in ids.values()) and len(set(ids.values())) == len(ids), "Hoenn block full"
        return ids

    # --- palettes
    def palettes(self):
        """{Emerald tag: (Hoenn tag, value, pal symbol, Emerald .pal, repo .pal)} of every palette the imported
        sprites use, append-only tag values (the 8 NPC palettes keep 0x1125-0x112C)."""
        mov = read(REPO / "src/event_object_movement.c")
        old = {n: int(v, 16) for n, v in re.findall(r"#define (OBJ_EVENT_PAL_TAG_HOENN_\w+)\s+(0x[0-9A-Fa-f]+)", mov)}
        tags = {"OBJ_EVENT_PAL_TAG_NPC_%d%s" % (n, r) for n in range(1, 5) for r in ("", "_REFLECTION")}  # Hoenn mode
        for g in self.scope:
            tag = self.em_info(g)["paletteTag"]
            tags.add(tag)
            if self.em_info(g)["paletteSlot"] == "PALSLOT_NPC_SPECIAL":
                tags.update(self.em_reflections.get(tag, []))
        out = {}
        for tag in sorted(tags, key=self.em_pal_tags.get):
            name = tag.replace("OBJ_EVENT_PAL_TAG_", "OBJ_EVENT_PAL_TAG_HOENN_")
            if name not in old:
                old[name] = max(old.values(), default=FIRST_PAL_TAG - 1) + 1
            em_pal = self.em.incbins[self.em_palettes[tag]].replace(".gbapal", ".pal")
            out[tag] = (name, old[name], hoenn(self.em_palettes[tag]), em_pal, PALS + "hoenn_" + Path(em_pal).name)
        assert len({v[1] for v in out.values()}) == len(out) and max(v[1] for v in out.values()) < 0x11FF
        return out

    def em_info(self, g):
        return self.em.infos[self.em.pointers["OBJ_EVENT_GFX_" + g]]

    # --- anims
    def anim_table(self, em_table):
        """(name used here, ported text or None): this repo's equivalent table, else Emerald's ported."""
        em_anims = [self.em.anims[a] for a in self.em.anim_tables[em_table]]
        em_step = self.em.steps.get(em_table)
        same = [n for n, fr in self.fr.anim_tables.items() if len(fr) >= len(em_anims) and self.fr.steps.get(n) == em_step
                and all(fr[i] and self.fr.anims[fr[i]] == a for i, a in enumerate(em_anims))]
        if same:  # the same name first, else the closest (fewest extra anims)
            return min(same, key=lambda n: (n != em_table, len(self.fr.anim_tables[n]))), None
        return hoenn(em_table), self.port(em_table, self.em.anims, self.fr.anims, "union AnimCmd")

    def affine_table(self, em_table):
        if em_table == "gDummySpriteAffineAnimTable":
            return em_table, None
        return hoenn(em_table), self.port(em_table, self.em.affine_anims, self.fr.affine_anims, "union AffineAnimCmd")

    def port(self, em_table, em_anims, fr_anims, ctype):
        """Emerald's table text (renamed), after the anims this repo lacks (same name and commands = shared)."""
        defs = definitions(self.em.anim_text, ctype)
        table_text = definitions(self.em.anim_text, r"%s \*const" % ctype)[em_table][0]
        text, done = [], set()
        for anim in re.findall(r"\b(s(?:Affine)?Anim_\w+)\b", uncomment(table_text)):
            if anim in done or fr_anims.get(anim) == em_anims[anim]:
                continue
            done.add(anim)
            text.append(re.sub(r"\b%s\b" % anim, hoenn(anim), defs[anim][0]))
        for anim in done:
            table_text = re.sub(r"\b%s\b" % anim, hoenn(anim), table_text)
        return "\n\n".join(text + [table_text.replace(em_table, hoenn(em_table), 1)]) + "\n"

    def max_frame(self, em_table, name, ported):
        """Highest frame index shown by the anim table used here: this repo's `name`, or Emerald's `em_table` ported."""
        tree, table = (self.em, em_table) if ported else (self.fr, name)
        return max(args[0][1] for a in tree.anim_tables[table] if a for c, args in tree.anims[a] if c == "ANIMCMD_FRAME")

    # --- everything
    def run(self):
        em, fr = self.em, self.fr
        pals = self.palettes()
        info_out, pic_out, gfx_out, rules, ports, steps, copies = [], [], [], [], {}, [], {}
        pic_names, pic_tables, rows = {}, {}, []
        frames_needed = {}
        anim_choice = {}
        for g in self.scope:
            info = self.em_info(g)
            if info["anims"] not in anim_choice:
                name, text = anim_choice[info["anims"]] = self.anim_table(info["anims"])
                if text:
                    ports[name] = text
                    if em.steps.get(info["anims"]):  # Emerald's step alternation for this table
                        steps.append("    {\n        .anims = %s,\n        .animPos = %s,\n    },\n" % (
                            name, em.steps[info["anims"]]))
            name, text = anim_choice[info["anims"]]
            frames_needed[info["images"]] = max(frames_needed.get(info["images"], 0),
                                                self.max_frame(info["anims"], name, text) + 1)
        for g in self.scope:
            info = self.em_info(g)
            assert sorted(info) == sorted(INFO_FIELDS) and info["tileTag"] == "TAG_NONE", (g, info)
            em_pic_table = info["images"]
            if em_pic_table not in pic_tables:
                lines = []
                for macro, args in em.pic_tables[em_pic_table]:
                    sym = args.split(",")[0].strip()
                    if sym not in pic_names:
                        src = em.incbins[sym].replace(".4bpp", ".png")
                        rel = src[len(PICS):].split("/", 1)[1]  # drop pics/<category>/
                        dst = PICS + "hoenn/" + rel
                        assert dst not in copies.values(), dst
                        copies[src] = dst
                        pic_names[sym] = (hoenn(sym), dst, src[len(PICS):].split("/")[0])
                        gfx_out.append('const u16 %s[] = INCBIN_U16("%s");\n' % (hoenn(sym), dst.replace(".png", ".4bpp")))
                        rule = self.em_rules.get(src[len(PICS):-4])  # none: the Makefile's %.4bpp: %.png, like Emerald
                        if rule:
                            rules.append("$(OBJEVENTGFXDIR)/%s.4bpp: %%.4bpp: %%.png\n\t$(GFX) $< $@ %s\n\n" % (
                                dst[len(PICS):-4], rule))
                    w, h = int(info["width"]), int(info["height"])
                    png = Image.open(em.root / em.incbins[sym].replace(".4bpp", ".png"))
                    if macro == "overworld_frame":
                        mw, mh, k = [int(a) for a in args.split(",")[1:]]
                        assert (mw * 8, mh * 8) == (w, h) and png.width * png.height >= (k + 1) * w * h, (g, args)
                    else:
                        assert png.size == (w, h), (g, png.size)
                    lines.append("    %s(%s),\n" % (macro, args.replace(sym, hoenn(sym), 1)))
                lines += [lines[0]] * (frames_needed[em_pic_table] - len(lines))
                pic_tables[em_pic_table] = len(lines)
                pic_out.append("static const struct SpriteFrameImage %s[] = {\n%s};\n\n" % (
                    hoenn(em_pic_table), "".join(lines)))
            tag = info["paletteTag"]
            refl = info["reflectionPaletteTag"]
            if refl != "OBJ_EVENT_PAL_TAG_NONE":  # this repo's palette of the same name (bridge_reflection.pal)
                em_pal = em.incbins[self.em_palettes[refl]].replace(".gbapal", ".pal")
                assert (em.root / em_pal).read_bytes() == (REPO / em_pal).read_bytes(), em_pal
            sub = info["subspriteTables"].replace("sOamTables_", "gObjectEventSpriteOamTables_")
            assert em.subsprites[info["subspriteTables"]] == fr.subsprites[sub], sub
            assert em.oams[info["oam"].lstrip("&")] == fr.oams[info["oam"].lstrip("&")], info["oam"]
            npc = re.fullmatch(r"OBJ_EVENT_PAL_TAG_NPC_(\d)", tag)  # NPC_N in slot N, a special palette in SPECIAL
            assert info["paletteSlot"] in (("PALSLOT_NPC_" + npc.group(1), "PALSLOT_NPC_SPECIAL") if npc
                                           else ("PALSLOT_NPC_SPECIAL",)), (g, tag, info["paletteSlot"])
            fields = dict(info, paletteTag=pals[tag][0], subspriteTables=sub, anims=anim_choice[info["anims"]][0],
                          images=hoenn(em_pic_table), affineAnims=self.affine_table(info["affineAnims"])[0])
            if info["affineAnims"] != "gDummySpriteAffineAnimTable":
                ports[fields["affineAnims"]] = self.affine_table(info["affineAnims"])[1]
            info_name = hoenn(em.pointers["OBJ_EVENT_GFX_" + g])
            info_out.append("const struct ObjectEventGraphicsInfo %s = {\n%s};\n\n" % (
                info_name, "".join("\t.%s = %s,\n" % (k, fields[k]) for k in INFO_FIELDS)))
            folder = pic_names[em.pic_tables[em_pic_table][0][1].split(",")[0].strip()][2]
            color = COLOR_BY_FOLDER.get(folder, "NPC_TEXT_COLOR_FEMALE" if g in FEMALE else "NPC_TEXT_COLOR_MALE")
            assert folder in ("people", "pokemon", "misc") and (folder == "people" or g not in FEMALE), (g, folder)
            rows.append(dict(gfx=g, id=self.ids[g], info=info_name, slot=info["paletteSlot"], tag=pals[tag][0],
                             frames=pic_tables[em_pic_table], em_frames=len(em.pic_tables[em_pic_table]),
                             size="%sx%s" % (info["width"], info["height"]), color=color, anims=fields["anims"]))
        self.rows = rows
        self.copies = copies
        self.pals = pals
        return self.blocks(info_out, pic_out, gfx_out, rules, ports, steps)

    def blocks(self, info_out, pic_out, gfx_out, rules, ports, steps):
        rows = sorted(self.rows, key=lambda r: r["id"])
        by_id = {r["id"]: r for r in rows}
        pals = sorted(self.pals.values(), key=lambda p: p[1])
        num = max([int(v) for v in re.findall(r"^[ \t]*#[ \t]*define[ \t]+OBJ_EVENT_GFX_\w+[ \t]+(\d+)\b",
                                              self.fr.ids_text, re.M)] + [r["id"] for r in rows]) + 1
        b = {}
        b["include/constants/event_objects.h", "ids"] = (
            "// pokeemerald object graphics for Hoenn maps: OBJ_EVENT_GFX_HOENN_X is Emerald's OBJ_EVENT_GFX_X (they use\n"
            "// Emerald's NPC palettes, see InitObjectEventPalettes). Append-only, like every id (see above)\n"
            + "".join("#define OBJ_EVENT_GFX_HOENN_%s %d\n" % (r["gfx"], r["id"]) for r in rows)
            + "\n#define NUM_OBJ_EVENT_GFX     %d // highest id + 1, all regions\n" % num)
        b[OBJ + "object_event_graphics.h", "graphics"] = "".join(
            'const u16 %s[] = INCBIN_U16("%s");\n' % (p[2], p[4].replace(".pal", ".gbapal")) for p in pals) + "".join(gfx_out)
        b[OBJ + "object_event_pic_tables.h", "pic tables"] = (
            "// Emerald's frames, then copies of frame 0 up to the last frame the anim table shows (no frame past the\n"
            "// table is ever read: this repo's sAnimTable_Standard shows frame 9 for ANIM_RAISE_HAND)\n" + "".join(pic_out))
        b[OBJ + "object_event_anims.h", "anims"] = "\n".join(ports[n] for n in sorted(ports))
        b[OBJ + "object_event_anims.h", "step anim tables"] = "".join(steps)
        b[OBJ + "object_event_graphics_info.h", "graphics infos"] = "".join(info_out)
        b[OBJ + "object_event_graphics_info_pointers.h", "declarations"] = "".join(
            "const struct ObjectEventGraphicsInfo %s;\n" % r["info"] for r in rows)
        b[OBJ + "object_event_graphics_info_pointers.h", "pointers"] = "".join(
            "    %-40s = &%s,\n" % ("[OBJ_EVENT_GFX_HOENN_%s]" % r["gfx"], r["info"]) for r in rows)
        fr_ids = defines(self.fr.ids_text)
        var = sorted(VARIANTS.items(), key=lambda kv: fr_ids("OBJ_EVENT_GFX_" + kv[0]))
        info_of = {r["gfx"]: r["info"] for r in rows}
        for k, v in var:  # a Kanto sprite drawn in an NPC palette slot (Hoenn maps load Emerald's palettes there)
            assert re.fullmatch(r"PALSLOT_NPC_\d", self.fr.infos[self.fr.pointers["OBJ_EVENT_GFX_" + k]]["paletteSlot"]) \
                and v in info_of, (k, v)
        b[OBJ + "object_event_graphics_info_pointers.h", "variants"] = (
            "// Hoenn maps (InitObjectEventPalettes(OBJ_PAL_MODE_HOENN)): the pokeemerald sprite a Kanto id shows there,\n"
            "// that of the same character class. A safety net: Hoenn maps use OBJ_EVENT_GFX_HOENN_ ids (hoenn_import.py\n"
            "// --check-gfx), but a Kanto id still drawn there (Porymap edit, save made before the map used Hoenn ids)\n"
            "// gets Emerald's sprite instead of wrong colors\n"
            "static const struct ObjectEventGraphicsInfo *const sHoennVariantGraphicsInfoPointers[NUM_OBJ_EVENT_GFX] = {\n"
            + "".join("    %-40s = &%s,\n" % ("[OBJ_EVENT_GFX_%s]" % k, info_of[v]) for k, v in var) + "};\n")
        b["src/event_object_movement.c", "palette tags"] = "".join("#define %-45s 0x%04X\n" % (p[0], p[1]) for p in pals)
        b["src/event_object_movement.c", "palettes"] = "".join(
            "    {%s%s},\n" % ((p[2] + ",").ljust(40) + " ", p[0]) for p in pals)
        # Emerald's reflection set of each special palette (LoadSpecialObjectReflectionPalette)
        special = {r["tag"] for r in self.rows if r["slot"] == "PALSLOT_NPC_SPECIAL"}
        refl = [(name, [self.pals[r][0] for r in self.em_reflections[t]], "sReflectionPaletteTags_" + camel(name[18:]))
                for t, (name, *_) in sorted(self.pals.items(), key=lambda kv: kv[1][1])
                if name in special and t in self.em_reflections]
        b["src/event_object_movement.c", "reflection palette tags"] = "".join(
            "static const u16 %s[] = {\n%s};\n\n" % (array, "".join("    %s,\n" % x for x in tags)) for _, tags, array in refl)
        b["src/event_object_movement.c", "reflection palette sets"] = "".join(
            "    {%s%s},\n" % ((name + ",").ljust(38) + " ", array) for name, _, array in refl)
        lines = []
        for even in range(HOENN_IDS.start, min(num, HOENN_IDS.stop), 2):  # the next region writes its own entries
            name = lambda i: "OBJ_EVENT_GFX_HOENN_" + by_id[i]["gfx"] if i in by_id else None
            color = lambda i: by_id[i]["color"] if i in by_id else "NPC_TEXT_COLOR_NEUTRAL"
            key = "[%s / 2]" % name(even) if name(even) else "[%d / 2]" % even
            lines.append("    %s= COLORS(%s, %s), // %s\n" % (key.ljust(43) + " ", color(even), color(even + 1),
                                                             name(even + 1) or "%d: none" % (even + 1)))
        b["src/dynamic_placeholder_text_util.c", "text colors"] = "".join(lines)
        b["spritesheet_rules.mk", "rules"] = "".join(rules)[:-1]
        return b


def splice(text, name, body, path):
    c = "#" if path.endswith(".mk") else "//"
    m = re.search(r"^([ \t]*)%s BEGIN %s: %s\n.*?^[ \t]*%s END %s: %s\n" % (
        c, re.escape(TOOL), re.escape(name), c, re.escape(TOOL), re.escape(name)), text, re.S | re.M)
    assert m, "%s: no '%s BEGIN %s: %s' / END lines" % (path, c, TOOL, name)
    ind = m.group(1)
    new = "%s%s BEGIN %s: %s\n%s%s%s END %s: %s\n" % (ind, c, TOOL, name, body, ind, c, TOOL, name)
    return text[:m.start()] + new + text[m.end():]


def main():
    if not __debug__:
        raise SystemExit("hoenn_sprites' safety checks are asserts: run it without python -O / PYTHONOPTIMIZE")
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("--emerald", type=Path, default=REPO.parent / "pokeemerald", help="pret/pokeemerald clone")
    parser.add_argument("--check", action="store_true", help="write nothing; exit 1 if a file would change")
    args = parser.parse_args()
    em = args.emerald.resolve()
    gen = Generator(em)
    blocks = gen.run()
    changed = []
    for path in dict.fromkeys(p for p, _ in blocks):
        text = read(REPO / path)  # read just before writing: other tools may edit these files too
        new = text
        for (p, name), body in blocks.items():
            if p == path:
                new = splice(new, name, body, path)
        if new != text:
            changed.append(path)
            if not args.check:
                with open(REPO / path, "w", encoding="utf-8", newline="") as f:
                    f.write(new)
    files = dict(gen.copies)
    files.update({p[3]: p[4] for p in gen.pals.values()})
    for src, dst in files.items():
        if not (REPO / dst).exists() or (REPO / dst).read_bytes() != (em / src).read_bytes():
            changed.append(dst)
            if not args.check:
                (REPO / dst).parent.mkdir(parents=True, exist_ok=True)
                shutil.copyfile(em / src, REPO / dst)
    rows = sorted(gen.rows, key=lambda r: r["id"])
    for r in rows:
        print("%3d OBJ_EVENT_GFX_HOENN_%-26s %-21s %-42s fr=%2d%s %-6s %-22s %s" % (
            r["id"], r["gfx"], r["slot"], r["tag"], r["frames"],
            "(+%d)" % (r["frames"] - r["em_frames"]) if r["frames"] > r["em_frames"] else "    ",
            r["size"], r["color"][len("NPC_TEXT_COLOR_"):], r["anims"]))
    print("%d Hoenn ids (%d..%d), %d free in the Hoenn block; %d palettes; %d variants" % (
        len(rows), rows[0]["id"], rows[-1]["id"], HOENN_IDS.stop - 1 - rows[-1]["id"], len(gen.pals), len(VARIANTS)))
    print(("would change: " if args.check else "changed: ") + (", ".join(changed) or "nothing"))
    if args.check and changed:
        sys.exit(1)


if __name__ == "__main__":
    main()
