LilycoveCity_CoveLilyMotel_2F_Text_ImTheProgrammer::
    .string "Moi? C'est à moi que tu parles?\n"
    .string "Je suis le PROGRAMMEUR.\p"
    .string "Je me demande à quoi ressemblent\n"
    .string "les MACHINES A SOUS ici.$"

LilycoveCity_CoveLilyMotel_2F_Text_ImTheGraphicArtist::
    .string "Je suis le GRAPHISTE! Les\n"
    .string "POKéMON de HOENN ne\l"
    .string "sont-ils pas intéressants?$"

LilycoveCity_CoveLilyMotel_2F_Text_GirlsAreCute::
    .string "Les filles FLOTTEURS sont à croquer,\n"
    .string "non? Pour affronter\l"
    .string "une de ces filles…\p"
    .string "Ouhhh, ça m'rend dingue!\p"
    .string "Et les JUMELLES! Mignonnes, hein? Un\n"
    .string "combat 2 contre 2\l"
    .string "avec les JUMELLES…\p"
    .string "Ouhhh, c'est terrible!$"

LilycoveCity_CoveLilyMotel_2F_Text_SeaBreezeTicklesHeart::
    .string "La brise marine emballe mon cœur.\n"
    .string "Quel bonheur d'être ici!$"

LilycoveCity_CoveLilyMotel_2F_Text_NeverLeaveWithoutGameBoy::
    .string "Tu ne peux pas savoir où et quand on\n"
    .string "va te défier.\p"
    .string "C'est pour cela que je ne sors jamais\n"
    .string "sans ma GAME BOY ADVANCE.$"

LilycoveCity_CoveLilyMotel_2F_Text_ShowMeCompletedDex::
    .string "Je suis le CONCEPTEUR DE JEU.\p"
    .string "Oh, est-ce que c'est vrai?\n"
    .string "Tu travailles sur un POKéDEX?\p"
    .string "C'est difficile de le compléter, mais\n"
    .string "n'abandonne pas.\p"
    .string "Si tu arrives à le compléter, reviens\n"
    .string "me voir.$"

LilycoveCity_CoveLilyMotel_2F_Text_FilledPokedexGiveYouThis::
    .string "Waouh! C'est impressionnant!\n"
    .string "Ouais, carrément impressionnant!\p"
    .string "Ce POKéDEX est totalement rempli!\n"
    .string "Tu dois vraiment aimer les POKéMON!\p"
    .string "Je suis si impressionné!\p"
    .string "Laisse-moi te donner quelque chose\n"
    .string "pour récompenser ton exploit!$"
