#ifndef GUARD_CONSTANTS_EVENT_OBJECTS_H
#define GUARD_CONSTANTS_EVENT_OBJECTS_H

#define OBJ_EVENT_GFX_RED_NORMAL 0
#define OBJ_EVENT_GFX_RED_BIKE 1
#define OBJ_EVENT_GFX_RED_SURF 2
#define OBJ_EVENT_GFX_RED_FIELD_MOVE 3
#define OBJ_EVENT_GFX_RED_FISH 4
#define OBJ_EVENT_GFX_RED_VS_SEEKER 5
#define OBJ_EVENT_GFX_RED_VS_SEEKER_BIKE 6
#define OBJ_EVENT_GFX_GREEN_NORMAL 7
#define OBJ_EVENT_GFX_GREEN_BIKE 8
#define OBJ_EVENT_GFX_GREEN_SURF 9
#define OBJ_EVENT_GFX_GREEN_FIELD_MOVE 10
#define OBJ_EVENT_GFX_GREEN_FISH 11
#define OBJ_EVENT_GFX_GREEN_VS_SEEKER 12
#define OBJ_EVENT_GFX_GREEN_VS_SEEKER_BIKE 13
#define OBJ_EVENT_GFX_RS_BRENDAN 14
#define OBJ_EVENT_GFX_RS_MAY 15
#define OBJ_EVENT_GFX_LITTLE_BOY 16
#define OBJ_EVENT_GFX_LITTLE_GIRL 17
#define OBJ_EVENT_GFX_YOUNGSTER 18
#define OBJ_EVENT_GFX_BOY 19
#define OBJ_EVENT_GFX_BUG_CATCHER 20
#define OBJ_EVENT_GFX_SITTING_BOY 21
#define OBJ_EVENT_GFX_LASS 22
#define OBJ_EVENT_GFX_WOMAN_1 23
#define OBJ_EVENT_GFX_BATTLE_GIRL 24
#define OBJ_EVENT_GFX_MAN 25
#define OBJ_EVENT_GFX_ROCKER 26
#define OBJ_EVENT_GFX_FAT_MAN 27
#define OBJ_EVENT_GFX_WOMAN_2 28
#define OBJ_EVENT_GFX_BEAUTY 29
#define OBJ_EVENT_GFX_BALDING_MAN 30
#define OBJ_EVENT_GFX_WOMAN_3 31
#define OBJ_EVENT_GFX_OLD_MAN_1 32
#define OBJ_EVENT_GFX_OLD_MAN_2 33
#define OBJ_EVENT_GFX_OLD_MAN_LYING_DOWN 34
#define OBJ_EVENT_GFX_OLD_WOMAN 35
#define OBJ_EVENT_GFX_TUBER_M_WATER 36
#define OBJ_EVENT_GFX_TUBER_F 37
#define OBJ_EVENT_GFX_TUBER_M_LAND 38
#define OBJ_EVENT_GFX_CAMPER 39
#define OBJ_EVENT_GFX_PICNICKER 40
#define OBJ_EVENT_GFX_COOLTRAINER_M 41
#define OBJ_EVENT_GFX_COOLTRAINER_F 42
#define OBJ_EVENT_GFX_SWIMMER_M_WATER 43
#define OBJ_EVENT_GFX_SWIMMER_F_WATER 44
#define OBJ_EVENT_GFX_SWIMMER_M_LAND 45
#define OBJ_EVENT_GFX_SWIMMER_F_LAND 46
#define OBJ_EVENT_GFX_WORKER_M 47
#define OBJ_EVENT_GFX_WORKER_F 48
#define OBJ_EVENT_GFX_ROCKET_M 49
#define OBJ_EVENT_GFX_ROCKET_F 50
#define OBJ_EVENT_GFX_GBA_KID 51
#define OBJ_EVENT_GFX_SUPER_NERD 52
#define OBJ_EVENT_GFX_BIKER 53
#define OBJ_EVENT_GFX_BLACKBELT 54
#define OBJ_EVENT_GFX_SCIENTIST 55
#define OBJ_EVENT_GFX_HIKER 56
#define OBJ_EVENT_GFX_FISHER 57
#define OBJ_EVENT_GFX_CHANNELER 58
#define OBJ_EVENT_GFX_CHEF 59
#define OBJ_EVENT_GFX_POLICEMAN 60
#define OBJ_EVENT_GFX_GENTLEMAN 61
#define OBJ_EVENT_GFX_SAILOR 62
#define OBJ_EVENT_GFX_CAPTAIN 63
#define OBJ_EVENT_GFX_NURSE 64
#define OBJ_EVENT_GFX_CABLE_CLUB_RECEPTIONIST 65
#define OBJ_EVENT_GFX_UNION_ROOM_RECEPTIONIST 66
#define OBJ_EVENT_GFX_UNUSED_MALE_RECEPTIONIST 67
#define OBJ_EVENT_GFX_CLERK 68
#define OBJ_EVENT_GFX_MG_DELIVERYMAN 69
#define OBJ_EVENT_GFX_TRAINER_TOWER_DUDE 70
#define OBJ_EVENT_GFX_PROF_OAK 71
#define OBJ_EVENT_GFX_BLUE 72
#define OBJ_EVENT_GFX_BILL 73
#define OBJ_EVENT_GFX_LANCE 74
#define OBJ_EVENT_GFX_AGATHA 75
#define OBJ_EVENT_GFX_DAISY 76
#define OBJ_EVENT_GFX_LORELEI 77
#define OBJ_EVENT_GFX_MR_FUJI 78
#define OBJ_EVENT_GFX_BRUNO 79
#define OBJ_EVENT_GFX_BROCK 80
#define OBJ_EVENT_GFX_MISTY 81
#define OBJ_EVENT_GFX_LT_SURGE 82
#define OBJ_EVENT_GFX_ERIKA 83
#define OBJ_EVENT_GFX_KOGA 84
#define OBJ_EVENT_GFX_SABRINA 85
#define OBJ_EVENT_GFX_BLAINE 86
#define OBJ_EVENT_GFX_GIOVANNI 87
#define OBJ_EVENT_GFX_MOM 88
#define OBJ_EVENT_GFX_CELIO 89
#define OBJ_EVENT_GFX_TEACHY_TV_HOST 90
#define OBJ_EVENT_GFX_GYM_GUY 91
#define OBJ_EVENT_GFX_ITEM_BALL 92
#define OBJ_EVENT_GFX_TOWN_MAP 93
#define OBJ_EVENT_GFX_POKEDEX 94
#define OBJ_EVENT_GFX_CUT_TREE 95
#define OBJ_EVENT_GFX_ROCK_SMASH_ROCK 96
#define OBJ_EVENT_GFX_PUSHABLE_BOULDER 97
#define OBJ_EVENT_GFX_FOSSIL 98
#define OBJ_EVENT_GFX_RUBY 99
#define OBJ_EVENT_GFX_SAPPHIRE 100
#define OBJ_EVENT_GFX_OLD_AMBER 101
#define OBJ_EVENT_GFX_GYM_SIGN 102
#define OBJ_EVENT_GFX_SIGN 103
#define OBJ_EVENT_GFX_TRAINER_TIPS 104
#define OBJ_EVENT_GFX_CLIPBOARD 105
#define OBJ_EVENT_GFX_METEORITE 106
#define OBJ_EVENT_GFX_LAPRAS_DOLL 107
#define OBJ_EVENT_GFX_SEAGALLOP 108
#define OBJ_EVENT_GFX_SNORLAX 109
#define OBJ_EVENT_GFX_SPEAROW 110
#define OBJ_EVENT_GFX_CUBONE 111
#define OBJ_EVENT_GFX_POLIWRATH 112
#define OBJ_EVENT_GFX_CLEFAIRY 113
#define OBJ_EVENT_GFX_PIDGEOT 114
#define OBJ_EVENT_GFX_JIGGLYPUFF 115
#define OBJ_EVENT_GFX_PIDGEY 116
#define OBJ_EVENT_GFX_CHANSEY 117
#define OBJ_EVENT_GFX_OMANYTE 118
#define OBJ_EVENT_GFX_KANGASKHAN 119
#define OBJ_EVENT_GFX_PIKACHU 120
#define OBJ_EVENT_GFX_PSYDUCK 121
#define OBJ_EVENT_GFX_NIDORAN_F 122
#define OBJ_EVENT_GFX_NIDORAN_M 123
#define OBJ_EVENT_GFX_NIDORINO 124
#define OBJ_EVENT_GFX_MEOWTH 125
#define OBJ_EVENT_GFX_SEEL 126
#define OBJ_EVENT_GFX_VOLTORB 127
#define OBJ_EVENT_GFX_SLOWPOKE 128
#define OBJ_EVENT_GFX_SLOWBRO 129
#define OBJ_EVENT_GFX_MACHOP 130
#define OBJ_EVENT_GFX_WIGGLYTUFF 131
#define OBJ_EVENT_GFX_DODUO 132
#define OBJ_EVENT_GFX_FEAROW 133
#define OBJ_EVENT_GFX_MACHOKE 134
#define OBJ_EVENT_GFX_LAPRAS 135
#define OBJ_EVENT_GFX_ZAPDOS 136
#define OBJ_EVENT_GFX_MOLTRES 137
#define OBJ_EVENT_GFX_ARTICUNO 138
#define OBJ_EVENT_GFX_MEWTWO 139
#define OBJ_EVENT_GFX_MEW 140
#define OBJ_EVENT_GFX_ENTEI 141
#define OBJ_EVENT_GFX_SUICUNE 142
#define OBJ_EVENT_GFX_RAIKOU 143
#define OBJ_EVENT_GFX_LUGIA 144
#define OBJ_EVENT_GFX_HO_OH 145
#define OBJ_EVENT_GFX_CELEBI 146
#define OBJ_EVENT_GFX_KABUTO 147
#define OBJ_EVENT_GFX_DEOXYS_D 148
#define OBJ_EVENT_GFX_DEOXYS_A 149
#define OBJ_EVENT_GFX_DEOXYS_N 150
#define OBJ_EVENT_GFX_SS_ANNE 151
#define OBJ_EVENT_GFX_CUE_BALL 152
#define OBJ_EVENT_GFX_PAINTER 153
#define OBJ_EVENT_GFX_BIRD_KEEPER 154
#define OBJ_EVENT_GFX_BURGLAR 155
#define OBJ_EVENT_GFX_POKEMON_RANGER_F 156
#define OBJ_EVENT_GFX_POKEMON_RANGER_M 157
#define OBJ_EVENT_GFX_RUIN_MANIAC 158
#define OBJ_EVENT_GFX_POKE_MANIAC 159
#define OBJ_EVENT_GFX_PSYCHIC_M 160
#define OBJ_EVENT_GFX_PSYCHIC_F 161
#define OBJ_EVENT_GFX_AROMA_LADY 162
#define OBJ_EVENT_GFX_TWIN 163
#define OBJ_EVENT_GFX_YOUNG_COUPLE_M 164
#define OBJ_EVENT_GFX_YOUNG_COUPLE_F 165
#define OBJ_EVENT_GFX_ENGINEER 166
#define OBJ_EVENT_GFX_JUGGLER 167
#define OBJ_EVENT_GFX_TAMER 168
#define OBJ_EVENT_GFX_POKEMON_BREEDER 169
#define OBJ_EVENT_GFX_RED_UNDERWATER 170
#define OBJ_EVENT_GFX_GREEN_UNDERWATER 171
#define OBJ_EVENT_GFX_SCOTT 172
#define OBJ_EVENT_GFX_BULBASAUR 173
#define OBJ_EVENT_GFX_CHARMANDER 174
#define OBJ_EVENT_GFX_SQUIRTLE 175
#define OBJ_EVENT_GFX_LATIAS 176
#define OBJ_EVENT_GFX_LATIOS 177
#define OBJ_EVENT_GFX_EM_BRENDAN 178
#define OBJ_EVENT_GFX_EM_MAY 179
#define OBJ_EVENT_GFX_CABLE_CAR 180
#define OBJ_EVENT_GFX_SUDOWOODO 181
#define OBJ_EVENT_GFX_ABRA 182
#define OBJ_EVENT_GFX_SWIMMER_F_WATER_2 183
#define OBJ_EVENT_GFX_MASTER_BEAUTY 184
#define OBJ_EVENT_GFX_MASTER_BIRD_KEEPER 185
#define OBJ_EVENT_GFX_MASTER_BLACK_BELT 186
#define OBJ_EVENT_GFX_MASTER_BUG_CATCHER 187
#define OBJ_EVENT_GFX_MASTER_COOLTRAINER_M 188
#define OBJ_EVENT_GFX_MASTER_HIKER 189
#define OBJ_EVENT_GFX_MASTER_LASS 190
#define OBJ_EVENT_GFX_MASTER_PSYCHIC_M 191
#define OBJ_EVENT_GFX_MASTER_SCIENTIST 192
#define OBJ_EVENT_GFX_MASTER_YOUNGSTER 193
#define OBJ_EVENT_GFX_LADY 194
#define OBJ_EVENT_GFX_ROCKER_2 195
#define OBJ_EVENT_GFX_ANABEL 196
#define OBJ_EVENT_GFX_TUCKER 197
#define OBJ_EVENT_GFX_GRETA 198
#define OBJ_EVENT_GFX_SPENSER 199
#define OBJ_EVENT_GFX_NOLAND 200
#define OBJ_EVENT_GFX_LUCY 201
#define OBJ_EVENT_GFX_BRANDON 202
// 203-208: reserved for OBJ_EVENT_GFX_KYOGRE..REGISTEEL (branch dev-regi)
// 209-239: free

// Graphics ids are u16 (storage: include/global.fieldmap.h) in region blocks of 256:
//   0-255 Kanto/FRLG (240-255: the OBJ_EVENT_GFX_VAR_x below), 256-511 Hoenn, 512-767 next region (Johto)...
// An id without a gObjectEventGraphicsInfoPointers entry draws OBJ_EVENT_GFX_LITTLE_BOY.
// Ids are stored in saves (objects, templates, quest log, VAR_OBJ_GFX_ID_x): never renumber or reuse an id
// once a released build used it; add new ids at the end of their region block.
#define HOENN_OBJ_EVENT_GFX_BASE 256
// BEGIN generated by tools/hoenn_import/hoenn_sprites.py: ids
// pokeemerald object graphics for Hoenn maps: OBJ_EVENT_GFX_HOENN_X is Emerald's OBJ_EVENT_GFX_X (they use
// Emerald's NPC palettes, see InitObjectEventPalettes). Append-only, like every id (see above)
#define OBJ_EVENT_GFX_HOENN_NINJA_BOY 256
#define OBJ_EVENT_GFX_HOENN_BOY_1 257
#define OBJ_EVENT_GFX_HOENN_GIRL_1 258
#define OBJ_EVENT_GFX_HOENN_BOY_2 259
#define OBJ_EVENT_GFX_HOENN_GIRL_2 260
#define OBJ_EVENT_GFX_HOENN_BOY_3 261
#define OBJ_EVENT_GFX_HOENN_GIRL_3 262
#define OBJ_EVENT_GFX_HOENN_RICH_BOY 263
#define OBJ_EVENT_GFX_HOENN_POKEFAN_F 264
#define OBJ_EVENT_GFX_HOENN_MAN_1 265
#define OBJ_EVENT_GFX_HOENN_EXPERT_M 266
#define OBJ_EVENT_GFX_HOENN_EXPERT_F 267
#define OBJ_EVENT_GFX_HOENN_MAN_2 268
#define OBJ_EVENT_GFX_HOENN_POKEFAN_M 269
#define OBJ_EVENT_GFX_HOENN_WOMAN_4 270
#define OBJ_EVENT_GFX_HOENN_MAN_3 271
#define OBJ_EVENT_GFX_HOENN_WOMAN_5 272
#define OBJ_EVENT_GFX_HOENN_SCHOOL_KID_M 273
#define OBJ_EVENT_GFX_HOENN_RUNNING_TRIATHLETE_M 274
#define OBJ_EVENT_GFX_HOENN_MAN_4 275
#define OBJ_EVENT_GFX_HOENN_CONTEST_JUDGE 276
#define OBJ_EVENT_GFX_HOENN_KECLEON 277
#define OBJ_EVENT_GFX_HOENN_AZUMARILL 278
#define OBJ_EVENT_GFX_HOENN_ARTIST 279
#define OBJ_EVENT_GFX_HOENN_QUINTY_PLUMP 280
#define OBJ_EVENT_GFX_HOENN_TWIN 281
#define OBJ_EVENT_GFX_HOENN_LITTLE_BOY 282
#define OBJ_EVENT_GFX_HOENN_LITTLE_GIRL 283
#define OBJ_EVENT_GFX_HOENN_WOMAN_1 284
#define OBJ_EVENT_GFX_HOENN_FAT_MAN 285
#define OBJ_EVENT_GFX_HOENN_WOMAN_2 286
#define OBJ_EVENT_GFX_HOENN_WOMAN_3 287
#define OBJ_EVENT_GFX_HOENN_COOK 288
#define OBJ_EVENT_GFX_HOENN_LINK_RECEPTIONIST 289
#define OBJ_EVENT_GFX_HOENN_OLD_MAN 290
#define OBJ_EVENT_GFX_HOENN_OLD_WOMAN 291
#define OBJ_EVENT_GFX_HOENN_CAMPER 292
#define OBJ_EVENT_GFX_HOENN_PICNICKER 293
#define OBJ_EVENT_GFX_HOENN_YOUNGSTER 294
#define OBJ_EVENT_GFX_HOENN_BUG_CATCHER 295
#define OBJ_EVENT_GFX_HOENN_PSYCHIC_M 296
#define OBJ_EVENT_GFX_HOENN_MANIAC 297
#define OBJ_EVENT_GFX_HOENN_HEX_MANIAC 298
#define OBJ_EVENT_GFX_HOENN_RAYQUAZA_STILL 299
#define OBJ_EVENT_GFX_HOENN_SWIMMER_M 300
#define OBJ_EVENT_GFX_HOENN_SWIMMER_F 301
#define OBJ_EVENT_GFX_HOENN_BLACK_BELT 302
#define OBJ_EVENT_GFX_HOENN_BEAUTY 303
#define OBJ_EVENT_GFX_HOENN_SCIENTIST_1 304
#define OBJ_EVENT_GFX_HOENN_LASS 305
#define OBJ_EVENT_GFX_HOENN_GENTLEMAN 306
#define OBJ_EVENT_GFX_HOENN_SAILOR 307
#define OBJ_EVENT_GFX_HOENN_FISHERMAN 308
#define OBJ_EVENT_GFX_HOENN_RUNNING_TRIATHLETE_F 309
#define OBJ_EVENT_GFX_HOENN_TUBER_F 310
#define OBJ_EVENT_GFX_HOENN_TUBER_M 311
#define OBJ_EVENT_GFX_HOENN_HIKER 312
#define OBJ_EVENT_GFX_HOENN_CYCLING_TRIATHLETE_M 313
#define OBJ_EVENT_GFX_HOENN_CYCLING_TRIATHLETE_F 314
#define OBJ_EVENT_GFX_HOENN_NURSE 315
#define OBJ_EVENT_GFX_HOENN_ITEM_BALL 316
#define OBJ_EVENT_GFX_HOENN_PROF_BIRCH 317
#define OBJ_EVENT_GFX_HOENN_MAN_5 318
#define OBJ_EVENT_GFX_HOENN_REPORTER_M 319
#define OBJ_EVENT_GFX_HOENN_REPORTER_F 320
#define OBJ_EVENT_GFX_HOENN_BARD 321
#define OBJ_EVENT_GFX_HOENN_ANABEL 322
#define OBJ_EVENT_GFX_HOENN_TUCKER 323
#define OBJ_EVENT_GFX_HOENN_GRETA 324
#define OBJ_EVENT_GFX_HOENN_SPENSER 325
#define OBJ_EVENT_GFX_HOENN_NOLAND 326
#define OBJ_EVENT_GFX_HOENN_LUCY 327
#define OBJ_EVENT_GFX_HOENN_CUTTABLE_TREE 328
#define OBJ_EVENT_GFX_HOENN_MART_EMPLOYEE 329
#define OBJ_EVENT_GFX_HOENN_ROOFTOP_SALE_WOMAN 330
#define OBJ_EVENT_GFX_HOENN_TEALA 331
#define OBJ_EVENT_GFX_HOENN_BREAKABLE_ROCK 332
#define OBJ_EVENT_GFX_HOENN_PUSHABLE_BOULDER 333
#define OBJ_EVENT_GFX_HOENN_MR_BRINEYS_BOAT 334
#define OBJ_EVENT_GFX_HOENN_TRUCK 335
#define OBJ_EVENT_GFX_HOENN_VIGOROTH_CARRYING_BOX 336
#define OBJ_EVENT_GFX_HOENN_VIGOROTH_FACING_AWAY 337
#define OBJ_EVENT_GFX_HOENN_BIRCHS_BAG 338
#define OBJ_EVENT_GFX_HOENN_ZIGZAGOON_1 339
#define OBJ_EVENT_GFX_HOENN_RIVAL_BRENDAN_NORMAL 340
#define OBJ_EVENT_GFX_HOENN_RIVAL_BRENDAN_MACH_BIKE 341
#define OBJ_EVENT_GFX_HOENN_RIVAL_BRENDAN_ACRO_BIKE 342
#define OBJ_EVENT_GFX_HOENN_RIVAL_BRENDAN_SURFING 343
#define OBJ_EVENT_GFX_HOENN_RIVAL_BRENDAN_FIELD_MOVE 344
#define OBJ_EVENT_GFX_HOENN_RIVAL_MAY_NORMAL 345
#define OBJ_EVENT_GFX_HOENN_RIVAL_MAY_MACH_BIKE 346
#define OBJ_EVENT_GFX_HOENN_RIVAL_MAY_ACRO_BIKE 347
#define OBJ_EVENT_GFX_HOENN_RIVAL_MAY_SURFING 348
#define OBJ_EVENT_GFX_HOENN_RIVAL_MAY_FIELD_MOVE 349
#define OBJ_EVENT_GFX_HOENN_CAMERAMAN 350
#define OBJ_EVENT_GFX_HOENN_MOVING_BOX 351
#define OBJ_EVENT_GFX_HOENN_CABLE_CAR 352
#define OBJ_EVENT_GFX_HOENN_SCIENTIST_2 353
#define OBJ_EVENT_GFX_HOENN_DEVON_EMPLOYEE 354
#define OBJ_EVENT_GFX_HOENN_AQUA_MEMBER_M 355
#define OBJ_EVENT_GFX_HOENN_AQUA_MEMBER_F 356
#define OBJ_EVENT_GFX_HOENN_MAGMA_MEMBER_M 357
#define OBJ_EVENT_GFX_HOENN_MAGMA_MEMBER_F 358
#define OBJ_EVENT_GFX_HOENN_SIDNEY 359
#define OBJ_EVENT_GFX_HOENN_PHOEBE 360
#define OBJ_EVENT_GFX_HOENN_GLACIA 361
#define OBJ_EVENT_GFX_HOENN_DRAKE 362
#define OBJ_EVENT_GFX_HOENN_ROXANNE 363
#define OBJ_EVENT_GFX_HOENN_BRAWLY 364
#define OBJ_EVENT_GFX_HOENN_WATTSON 365
#define OBJ_EVENT_GFX_HOENN_FLANNERY 366
#define OBJ_EVENT_GFX_HOENN_NORMAN 367
#define OBJ_EVENT_GFX_HOENN_WINONA 368
#define OBJ_EVENT_GFX_HOENN_LIZA 369
#define OBJ_EVENT_GFX_HOENN_TATE 370
#define OBJ_EVENT_GFX_HOENN_WALLACE 371
#define OBJ_EVENT_GFX_HOENN_STEVEN 372
#define OBJ_EVENT_GFX_HOENN_WALLY 373
#define OBJ_EVENT_GFX_HOENN_LITTLE_BOY_3 374
#define OBJ_EVENT_GFX_HOENN_HOT_SPRINGS_OLD_WOMAN 375
#define OBJ_EVENT_GFX_HOENN_SS_TIDAL 376
#define OBJ_EVENT_GFX_HOENN_SUBMARINE_SHADOW 377
#define OBJ_EVENT_GFX_HOENN_LATIAS 378
#define OBJ_EVENT_GFX_HOENN_LATIOS 379
#define OBJ_EVENT_GFX_HOENN_GAMEBOY_KID 380
#define OBJ_EVENT_GFX_HOENN_ARCHIE 381
#define OBJ_EVENT_GFX_HOENN_MAXIE 382
#define OBJ_EVENT_GFX_HOENN_KYOGRE_FRONT 383
#define OBJ_EVENT_GFX_HOENN_GROUDON_FRONT 384
#define OBJ_EVENT_GFX_HOENN_FOSSIL 385
#define OBJ_EVENT_GFX_HOENN_REGIROCK 386
#define OBJ_EVENT_GFX_HOENN_REGICE 387
#define OBJ_EVENT_GFX_HOENN_REGISTEEL 388
#define OBJ_EVENT_GFX_HOENN_SKITTY 389
#define OBJ_EVENT_GFX_HOENN_KYOGRE_ASLEEP 390
#define OBJ_EVENT_GFX_HOENN_GROUDON_ASLEEP 391
#define OBJ_EVENT_GFX_HOENN_RAYQUAZA 392
#define OBJ_EVENT_GFX_HOENN_ZIGZAGOON_2 393
#define OBJ_EVENT_GFX_HOENN_PIKACHU 394
#define OBJ_EVENT_GFX_HOENN_WINGULL 395
#define OBJ_EVENT_GFX_HOENN_KECLEON_BRIDGE_SHADOW 396
#define OBJ_EVENT_GFX_HOENN_TUBER_M_SWIMMING 397
#define OBJ_EVENT_GFX_HOENN_AZURILL 398
#define OBJ_EVENT_GFX_HOENN_MOM 399
#define OBJ_EVENT_GFX_HOENN_JUAN 400
#define OBJ_EVENT_GFX_HOENN_SCOTT 401
#define OBJ_EVENT_GFX_HOENN_POOCHYENA 402
#define OBJ_EVENT_GFX_HOENN_KYOGRE_SIDE 403
#define OBJ_EVENT_GFX_HOENN_GROUDON_SIDE 404
#define OBJ_EVENT_GFX_HOENN_MYSTERY_GIFT_MAN 405
#define OBJ_EVENT_GFX_HOENN_TRICK_HOUSE_STATUE 406
#define OBJ_EVENT_GFX_HOENN_KIRLIA 407
#define OBJ_EVENT_GFX_HOENN_DUSCLOPS 408
#define OBJ_EVENT_GFX_HOENN_UNION_ROOM_NURSE 409
#define OBJ_EVENT_GFX_HOENN_SUDOWOODO 410
#define OBJ_EVENT_GFX_HOENN_MEW 411
#define OBJ_EVENT_GFX_HOENN_DEOXYS 412
#define OBJ_EVENT_GFX_HOENN_DEOXYS_TRIANGLE 413
#define OBJ_EVENT_GFX_HOENN_BRANDON 414
#define OBJ_EVENT_GFX_HOENN_LUGIA 415
#define OBJ_EVENT_GFX_HOENN_HOOH 416

#define NUM_OBJ_EVENT_GFX     417 // highest id + 1, all regions
// END generated by tools/hoenn_import/hoenn_sprites.py: ids

// These are dynamic object gfx ids.
// They correspond with the values of the VAR_OBJ_GFX_ID_X vars.
// Only the Kanto block's 240-255 are dynamic: ids of other regions are never VAR ids.
// More info about them in include/constants/vars.h
#define OBJ_EVENT_GFX_VARS   240
#define OBJ_EVENT_GFX_VAR_0  (OBJ_EVENT_GFX_VARS + 0x0) // 240
#define OBJ_EVENT_GFX_VAR_1  (OBJ_EVENT_GFX_VARS + 0x1)
#define OBJ_EVENT_GFX_VAR_2  (OBJ_EVENT_GFX_VARS + 0x2)
#define OBJ_EVENT_GFX_VAR_3  (OBJ_EVENT_GFX_VARS + 0x3)
#define OBJ_EVENT_GFX_VAR_4  (OBJ_EVENT_GFX_VARS + 0x4)
#define OBJ_EVENT_GFX_VAR_5  (OBJ_EVENT_GFX_VARS + 0x5)
#define OBJ_EVENT_GFX_VAR_6  (OBJ_EVENT_GFX_VARS + 0x6)
#define OBJ_EVENT_GFX_VAR_7  (OBJ_EVENT_GFX_VARS + 0x7)
#define OBJ_EVENT_GFX_VAR_8  (OBJ_EVENT_GFX_VARS + 0x8)
#define OBJ_EVENT_GFX_VAR_9  (OBJ_EVENT_GFX_VARS + 0x9)
#define OBJ_EVENT_GFX_VAR_A  (OBJ_EVENT_GFX_VARS + 0xA)
#define OBJ_EVENT_GFX_VAR_B  (OBJ_EVENT_GFX_VARS + 0xB)
#define OBJ_EVENT_GFX_VAR_C  (OBJ_EVENT_GFX_VARS + 0xC)
#define OBJ_EVENT_GFX_VAR_D  (OBJ_EVENT_GFX_VARS + 0xD)
#define OBJ_EVENT_GFX_VAR_E  (OBJ_EVENT_GFX_VARS + 0xE)
#define OBJ_EVENT_GFX_VAR_F  (OBJ_EVENT_GFX_VARS + 0xF) // 255

#define SHADOW_SIZE_S   0
#define SHADOW_SIZE_M   1
#define SHADOW_SIZE_L   2
#define SHADOW_SIZE_XL  3

#define F_INANIMATE                        (1 << 6)
#define F_DISABLE_REFLECTION_PALETTE_LOAD  (1 << 7)

#define TRACKS_NONE       0
#define TRACKS_FOOT       1
#define TRACKS_BIKE_TIRE  2

#define OBJ_KIND_NORMAL 0
#define OBJ_KIND_CLONE  255

// Special object event local ids
#define OBJ_EVENT_ID_PLAYER  0xFF
#define OBJ_EVENT_ID_CAMERA  0x7F

// Object event local ids referenced in C files
#define LOCALID_UNION_ROOM_PLAYER_4 2
#define LOCALID_UNION_ROOM_PLAYER_8 3
#define LOCALID_UNION_ROOM_PLAYER_7 4
#define LOCALID_UNION_ROOM_PLAYER_6 5
#define LOCALID_UNION_ROOM_PLAYER_5 6
#define LOCALID_UNION_ROOM_PLAYER_3 7
#define LOCALID_UNION_ROOM_PLAYER_2 8
#define LOCALID_UNION_ROOM_PLAYER_1 9

#endif // GUARD_CONSTANTS_EVENT_OBJECTS_H
