LilycoveCity_DepartmentStore_5F_Text_GettingDollInsteadOfPokemon::
    .string "J'suis trop petite pour un POKéMON,\n"
    .string "alors je prends une adorable POUPEE.$"

LilycoveCity_DepartmentStore_5F_Text_PlaceFullOfCuteDolls::
    .string "Ce lieu regorge\n"
    .string "d'adorables POUPEES.\p"
    .string "Je devrais aussi en acheter pour moi\n"
    .string "et pas que pour les enfants.$"

LilycoveCity_DepartmentStore_5F_Text_SellManyCuteMatsHere::
    .string "Ils vendent plein de\n"
    .string "super TAPIS ici.\p"
    .string "Je me demande lequel je\n"
    .string "vais prendre. Je vais\l"
    .string "peut-être tous les acheter…$"
