LilycoveCity_ContestHall_Text_TodayWonSmartnessContest::
    .string "Ce POKéMON a déjà gagné le CONCOURS\n"
    .string "DE BEAUTE ici.\p"
    .string "Et tu sais quoi? Je lui ai\n"
    .string "fait gagner le CONCOURS\l"
    .string "D'INTELLIGENCE, aujourd'hui!\p"
    .string "Je m'effraie moi-même…$"

LilycoveCity_ContestHall_Text_EnteredBunchOfContests::
    .string "J'ai fait pas mal de CONCOURS,\n"
    .string "donc je sais comment ça se passe.\p"
    .string "Dans un CONCOURS DE SANG-FROID, les\n"
    .string "capacités SANG-FROID\l"
    .string "ont du succès.\p"
    .string "Mais les capacités INTELLIGENCE et\n"
    .string "GRACE, par exemple, n'ont pas trop\l"
    .string "d'effet.$"

LilycoveCity_ContestHall_Text_ManWhoWonEarlierHadPokeblocks::
    .string "Le jeune garçon qui vient de gagner\n"
    .string "avait plein de\l"
    .string "POKéBLOCS différents.\p"
    .string "Tu gagnerais, toi,\n"
    .string "si t'en avais autant?$"

LilycoveCity_ContestHall_Text_IsntThisPlaceHumongous::
    .string "Waouh, cet endroit est super!\p"
    .string "On peut sentir la tension dans l'air…\n"
    .string "Ça, c'est un vrai lieu de CONCOURS.$"

LilycoveCity_ContestHall_Text_GiveItBestSmartAppeal::
    .string "ANIMATRICE: POKéMON INTELLIGENTS\n"
    .string "et leurs DRESSEURS,\l"
    .string "vous êtes prêts?!\p"
    .string "Montrez-vous sous votre meilleur\n"
    .string "jour! C'est parti!$"

LilycoveCity_ContestHall_Text_AreYouEnjoyingThisContest::
    .string "JUGE: Vous aimez ce\n"
    .string "genre de CONCOURS?\p"
    .string "Revenez avec trois amis et vous\n"
    .string "pourrez tous participer\l"
    .string "à un CONCOURS!$"

LilycoveCity_ContestHall_Text_EnteredWrongContest::
    .string "Aïe, aïe, aïe…\n"
    .string "Je me suis trompé de CONCOURS.\p"
    .string "J'ai inscrit ce POKéMON ROBUSTE à un\n"
    .string "CONCOURS D'INTELLIGENCE…\p"
    .string "Allez, montre-leur ton ECLATE-ROC.$"

LilycoveCity_ContestHall_Text_RaisedMonToBeSmart::
    .string "Cela m'a pris des années et beaucoup\n"
    .string "de sagesse, pour que ce POKéMON\l"
    .string "devienne aussi intelligent.\p"
    .string "Il ne se laisse pas battre par\n"
    .string "n'importe quel POKéMON inexpérimenté.$"

LilycoveCity_ContestHall_Text_IfMonPullsSmartMoveNext::
    .string "Voilà!\p"
    .string "Une capacité INTELLIGENCE\n"
    .string "maintenant, et l'enthousiasme\l"
    .string "du public augmentera!$"

LilycoveCity_ContestHall_Text_DontAppreciateCuteLeechLife::
    .string "Oh, non!\p"
    .string "J'utilise tout le temps le VAMPIRISME\n"
    .string "de mon NOSFERAPTI,\l"
    .string "il est si gracieux!\p"
    .string "Mais ces gens sont méchants et\n"
    .string "n'apprécient pas du tout!$"

LilycoveCity_ContestHall_Text_YoureBeautifulGrandpa::
    .string "Ouais! T'es super, pépé!$"

LilycoveCity_ContestHall_Text_AllSeemToUseDifferentMoves::
    .string "Même quand les DRESSEURS inscrivent\n"
    .string "le même genre de POKéMON,\l"
    .string "ils semblent utiliser des\l"
    .string "capacités différentes.\p"
    .string "C'est comme pour les combats, chacun\n"
    .string "a son propre style.$"

LilycoveCity_ContestHall_Text_PokemonSmarterThanTrainers::
    .string "Je trouve que les POKéMON ont\n"
    .string "l'air bien plus intelligents\l"
    .string "que leurs DRESSEURS.$"

LilycoveCity_ContestHall_Text_StillLoveSmartnessContests::
    .string "Par-dessus tout, j'adore les\n"
    .string "CONCOURS D'INTELLIGENCE.\p"
    .string "Cette couleur verte si\n"
    .string "intellectuelle… C'est… super cool.$"

LilycoveCity_ContestHall_Text_AreYouEnteringBeautyContest::
    .string "ANIMATRICE: Tu vas aussi\n"
    .string "participer au CONCOURS\l"
    .string "DE BEAUTE? Bonne chance!$"

LilycoveCity_ContestHall_Text_EveryPokemonPristineBeauty::
    .string "JUGE: Ah, les POKéMON ici présents\n"
    .string "sont des spécimens\l"
    .string "d'une rare beauté!\p"
    .string "Oh, j'en ai presque\n"
    .string "oublié de les noter!$"

LilycoveCity_ContestHall_Text_EyesWillBeGluedToMyBeauty::
    .string "Un POKéMON de cette magnificence…\n"
    .string "Il n'y en a pas deux comme ça.\p"
    .string "Tout le monde sera subjugué par tant\n"
    .string "de beauté.$"

LilycoveCity_ContestHall_Text_OverdidGrooming::
    .string "Ahhhhh!\p"
    .string "J'ai brossé et coiffé mon POKéMON\n"
    .string "avec soin pour ce CONCOURS…\p"
    .string "Mais j'ai exagéré…\n"
    .string "Maintenant, il a le\l"
    .string "poil tout ébouriffé…\p"
    .string "Qu'est-ce que je peux faire?$"

LilycoveCity_ContestHall_Text_JudgeWontSeeAuroraBeam::
    .string "Cette ONDE BOREALE est si\n"
    .string "éblouissante que le JUGE\l"
    .string "ne pourra pas la voir.\p"
    .string "Euh, attends…\n"
    .string "Mais ça sert à rien, alors!$"

LilycoveCity_ContestHall_Text_PokemonLooksLikeYoungerMe::
    .string "Ce joli POKéMON, c'est exactement moi\n"
    .string "quand j'étais plus jeune.\p"
    .string "Juste au moment où je l'ai dit, mon\n"
    .string "mari s'est étouffé avec son café.\p"
    .string "J'ai dit quelque chose d'amusant?$"

LilycoveCity_ContestHall_Text_WinBeautyContestMakesMeHappy::
    .string "Tu sais, en tant que femme, je serais\n"
    .string "plus qu'heureuse de gagner un\l"
    .string "CONCOURS DE BEAUTE.$"

LilycoveCity_ContestHall_Text_GanderAtAllThosePrettyPokemon::
    .string "Waouhhhh!\p"
    .string "Tu devrais jeter un coup d'œil\n"
    .string "à ces jolis POKéMON.\p"
    .string "Quelle splendeur! J'adore!$"

LilycoveCity_ContestHall_Text_CantWinOnBeautyAlone::
    .string "Tu ne peux pas toujours compter\n"
    .string "sur la beauté uniquement.\p"
    .string "Tu dois aussi coiffer ton\n"
    .string "POKéMON, pour qu'il soit\l"
    .string "aussi brillant que le mien.$"

LilycoveCity_ContestHall_Text_InTheMiddleOfContest::
    .string "ANIMATRICE: Hum! Ohé!\n"
    .string "On est en plein CONCOURS!\p"
    .string "Veuillez vous inscrire au guichet et\n"
    .string "revenez ensuite, vous voulez bien?$"

LilycoveCity_ContestHall_Text_SuchCharmingCuteAppeals::
    .string "JUGE: Oh, quelles démonstrations\n"
    .string "ravissantes et gracieuses!\p"
    .string "Juste ciel! Quelle\n"
    .string "parfaite et adorable\l"
    .string "démonstration de TOURNIQUET!$"

LilycoveCity_ContestHall_Text_MyAzurillWasDistracted::
    .string "Oh, non… Mon doux AZURILL s'est\n"
    .string "laissé distraire par\l"
    .string "un autre POKéMON.$"

LilycoveCity_ContestHall_Text_NeverWonBattleButContest::
    .string "Mon POKéMON ne gagne\n"
    .string "jamais de combat, mais en\l"
    .string "CONCOURS, c'est le meilleur!$"

LilycoveCity_ContestHall_Text_PetalDanceIsMarvel::
    .string "La DANSE-FLEUR de mon POKéMON est\n"
    .string "une merveille d'élégance.\p"
    .string "Je ne laisserai personne perturber sa\n"
    .string "prestation.$"

LilycoveCity_ContestHall_Text_MyMonAppealSoMuchCuter::
    .string "Tous les POKéMON sont gracieux.\p"
    .string "Mais si mon POKéMON faisait une\n"
    .string "démonstration de grâce…\p"
    .string "Je suis sûre qu'il serait beaucoup\n"
    .string "plus gracieux que les autres.$"

LilycoveCity_ContestHall_Text_MyChildIsInContest::
    .string "Mon enfant participe au CONCOURS.$"

LilycoveCity_ContestHall_Text_ComeOnDear::
    .string "Vas-y, courage!\n"
    .string "Ton POKéMON est le meilleur!$"

LilycoveCity_ContestHall_Text_WantCuteMonOfMyOwn::
    .string "Oh, regarder tous ces\n"
    .string "gracieux POKéMON me\l"
    .string "donne envie d'en avoir un!\p"
    .string "Je vais aller en\n"
    .string "attraper quelques-uns!$"

LilycoveCity_ContestHall_Text_ThatGirlThereIsCutest::
    .string "Je trouve que cette fille est\n"
    .string "vraiment la plus gracieuse.\p"
    .string "Comment? Ils jugent les POKéMON\n"
    .string "sur leur apparence?$"

LilycoveCity_ContestHall_Text_BeautyContestStage::
    .string "EPREUVE DE BEAUTE\n"
    .string "POKéMON D'UNE BEAUTE\l"
    .string "EPOUSTOUFLANTE!$"

LilycoveCity_ContestHall_Text_CuteContestStage::
    .string "EPREUVE DE GRACE\n"
    .string "POKéMON D'UNE GRACE EXTREME!$"

LilycoveCity_ContestHall_Text_SmartContestStage::
    .string "EPREUVE D'INTELLIGENCE\n"
    .string "POKéMON D'UNE INTELLIGENCE INOUIE!$"
