LilycoveCity_PokemonTrainerFanClub_Text_ImPullingForYou::
    .string "Oh!\n"
    .string "{PLAYER}!\p"
    .string "Vas-y!\n"
    .string "Je te soutiens!$"

@ Adapted (RFVF+): Emerald's "your own father" (NORMAN, Emerald's hero's father) -> "the best TRAINERS"
LilycoveCity_PokemonTrainerFanClub_Text_YouveSurpassedYourFather::
    .string "Tu surpasses les meilleurs DRESSEURS\n"
    .string "à tous les égards!\p"
    .string "Je t'assure, il n'y a aucun doute\n"
    .string "là-dessus!$"

LilycoveCity_PokemonTrainerFanClub_Text_OhWoweeItsPlayer::
    .string "Oh, youhouh! C'est {PLAYER}!\n"
    .string "En vrai!\p"
    .string "Serre-moi la main, serre-moi la main!$"

LilycoveCity_PokemonTrainerFanClub_Text_WantToBeStrongLikeYou::
    .string "Waouh! C'est {PLAYER}!\n"
    .string "Génial!\p"
    .string "Quand je serai grand, je veux être\n"
    .string "aussi fort que toi, {PLAYER}!$"

LilycoveCity_PokemonTrainerFanClub_Text_YoureAmazingAfterAll::
    .string "{PLAYER}! Tu es vraiment quelqu'un\n"
    .string "d'exceptionnel!\p"
    .string "Dès que j'ai posé les yeux sur toi,\n"
    .string "j'ai su que tu étais remarquable.\p"
    .string "Apparemment, j'ai vu juste.$"

LilycoveCity_PokemonTrainerFanClub_Text_YoureOneWeWantToWin::
    .string "Yé, {PLAYER}!\n"
    .string "On veut te voir gagner!$"

LilycoveCity_PokemonTrainerFanClub_Text_YouChangedMyMind::
    .string "Tu m'as fait changer d'avis!\n"
    .string "Tu es robuste, hein?\p"
    .string "J'aimerais bien que tu m'expliques\n"
    .string "comment tu as pu devenir si balèze!$"

LilycoveCity_PokemonTrainerFanClub_Text_YouImpressive::
    .string "Tu…\p"
    .string "Impressionnant!$"
