LilycoveCity_Text_ContestHallInTown::
    .string "Il y a une SALLE DE CONCOURS\n"
    .string "POKéMON dans cette ville.\p"
    .string "Ça veut dire qu'on peut y voir des\n"
    .string "POKéMON bien dressés venant\l"
    .string "des quatre coins du pays.\p"
    .string "Mon cœur déborde d'enthousiasme!$"

LilycoveCity_Text_GoingToMoveDeleterForHMs::
    .string "Je vais apprendre de nouvelles\n"
    .string "capacités à mon POKéMON pour\l"
    .string "qu'il participe à un CONCOURS.\p"
    .string "Alors je vais aller voir l'EFFACEUR\n"
    .string "DE CAPACITES, pour qu'il lui fasse\l"
    .string "oublier certaines CS.$"

LilycoveCity_Text_ImFromKanto::
    .string "Je viens de KANTO.\p"
    .string "La région de HOENN est très belle\n"
    .string "avec son eau et sa\l"
    .string "nature verdoyante.\p"
    .string "Hum? Attends une seconde…\p"
    .string "Y aurait-il des POKéMON rares qui\n"
    .string "ne vivent que dans cette zone?$"

LilycoveCity_Text_SomeonePuntedTeamAquaOut::
    .string "Eh, t'es au courant?\p"
    .string "Quelqu'un a chassé la TEAM AQUA\n"
    .string "de la voie que nous empruntons!\p"
    .string "Les WAILMER ne sont plus dans la\n"
    .string "crique, alors on peut à nouveau\l"
    .string "sortir en mer.$"

LilycoveCity_Text_MissingPokemonCameBack::
    .string "Le POKéMON qui me manquait…\n"
    .string "Il est revenu sans\l"
    .string "que j'm'en aperçoive!$"

LilycoveCity_Text_ImArtDealer::
    .string "Je suis MARCHAND D'ART.\p"
    .string "J'achète et je vends des œuvres\n"
    .string "d'art, essentiellement des tableaux.\p"
    .string "J'ai entendu dire que le MUSEE, ici,\n"
    .string "exposait de magnifiques œuvres…$"

LilycoveCity_Text_SeaRemainsForeverYoung::
    .string "Même quand on vieillit et qu'on\n"
    .string "devient tout ridé, la mer\l"
    .string "semble toujours jeune grâce\l"
    .string "à l'éclat radieux de la vie…\p"
    .string "Oh, oh, oh…$"

LilycoveCity_Text_SixtyYearsAgoHusbandProposed::
    .string "Il y a soixante ans, mon mari m'a\n"
    .string "demandée en mariage ici.\l"
    .string "La mer est toujours aussi belle.\p"
    .string "Aaaaaaaaaaaah…$"

LilycoveCity_Text_TeamAquaLotGoneForGood::
    .string "Cette caverne dans la crique…\p"
    .string "Je n'avais pas remarqué, mais elle\n"
    .string "est complètement vide maintenant.\p"
    .string "Ces vauriens de la TEAM AQUA, ils ont\n"
    .string "dû partir pour de bon.$"

LilycoveCity_Text_HeardTowerCalledSkyPillar::
    .string "J'ai entendu dire qu'il y aurait une\n"
    .string "tour au-delà de la mer.\p"
    .string "Je crois qu'on l'appelle le PILIER\n"
    .string "CELESTE.$"

LilycoveCity_Text_SawTallTowerOnRoute131::
    .string "J'ai vu cette tour immense quelque\n"
    .string "part près du CHENAL 131.\p"
    .string "Est-ce possible?$"

LilycoveCity_Text_JustArrivedAndSawRarePokemon::
    .string "On vient juste d'arriver ici pour\n"
    .string "passer notre lune de miel.\p"
    .string "Et on a vu un POKéMON\n"
    .string "du type DRAGON voler\l"
    .string "très haut dans le ciel.\p"
    .string "Il y a vraiment des POKéMON comme\n"
    .string "ça à HOENN?$"

LilycoveCity_Text_HoneymoonVowToSeeRarePokemon::
    .string "Pour notre lune de miel, on\n"
    .string "a l'intention de voir autant\l"
    .string "de POKéMON que possible.\p"
    .string "Alors imagine un peu ce qu'on a pu\n"
    .string "ressentir en voyant\l"
    .string "ce POKéMON rare.\p"
    .string "Il n'y a pas de mots\n"
    .string "pour l'expliquer!$"

LilycoveCity_Text_DoYouKnowAboutBerryBlender::
    .string "Tu connais cet appareil appelé\n"
    .string "MIXEUR?$"

LilycoveCity_Text_FasterSpinBetterPokeblocks::
    .string "Il faut s'y mettre à plusieurs pour\n"
    .string "que ça tourne plus vite.\p"
    .string "J'ai entendu dire que plus ça tourne\n"
    .string "vite, meilleurs sont les POKéBLOCS.$"

LilycoveCity_Text_ExplainBerryBlender::
    .string "On l'utilise pour fabriquer une sorte\n"
    .string "de bonbon appelé POKéBLOC.\p"
    .string "Si tu donnes un bon POKéBLOC à un\n"
    .string "POKéMON, sa condition va s'améliorer.$"

LilycoveCity_Text_CitySign::
    .string "NENUCRIQUE\p"
    .string "“Là où la terre s'arrête, là où la\n"
    .string "mer commence.”$"

LilycoveCity_Text_ContestHallSign::
    .string "CONCOURS POKéMON\n"
    .string "“Participez aux CONCOURS avec\l"
    .string "vos amis!”$"

LilycoveCity_Text_MotelSign::
    .string "HOTEL CRIQUE CRACK\p"
    .string "“Souvenez-vous de nous comme les\n"
    .string "cracks de la crique.”$"

LilycoveCity_Text_MuseumSign::
    .string "MUSEE NENUCRIQUE\p"
    .string "“Exposition de la collection de\n"
    .string "chefs-d'œuvre POKéMON.”$"

@ Adapted (RFVF+): Emerald's ferry LE MARINA -> the FLECHE DES MERS to CARMIN SUR MER
LilycoveCity_Text_HarborSign::
    .string "EMBARCADERE DE NENUCRIQUE\p"
    .string "“Profitez d'une merveilleuse\n"
    .string "croisière vers CARMIN SUR MER\l"
    .string "à bord de la FLECHE DES MERS.”$"

LilycoveCity_Text_TrainerFanClubSign::
    .string "FAN CLUB DES DRESSEURS POKéMON\p"
    .string "Des noms de DRESSEURS parsèment le\n"
    .string "panneau…$"

LilycoveCity_Text_DepartmentStoreSign::
    .string "CENTRE COMMERCIAL NENUCRIQUE\p"
    .string "“Marchandises à profusion\n"
    .string "et débordement d'enthousiasme!”\p"
    .string "“L'endroit idéal pour trouver tout\n"
    .string "ce qu'il vous faut!”$"

LilycoveCity_Text_MoveDeletersHouseSign::
    .string "MAISON DE L'EFFACEUR DE CAPACITES\p"
    .string "“Toutes les capacités de POKéMON\n"
    .string "non désirées sont oubliées!”$"

LilycoveCity_Text_BerrySuitsYou::
    .string "Quand on y regarde de près…\p"
    .string "les costumes me conviennent\n"
    .string "parfaitement.\p"
    .string "Et toi, une BAIE, ça te convient…\p"
    .string "Et pourquoi donc?$"

LilycoveCity_Text_BecauseYoureTrainer::
    .string "Si on veut trouver une explication…\p"
    .string "c'est parce que tu es DRESSEUR!$"

LilycoveCity_Text_PokeblocksSuitPokemon::
    .string "Quand on y regarde de près…\p"
    .string "tout comme la simplicité me va, les\n"
    .string "POKéBLOCS conviennent très bien aux\l"
    .string "POKéMON.$"
