LilycoveCity_DepartmentStore_3F_Text_ItemsBestForTougheningPokemon::
    .string "Pour endurcir les POKéMON en un rien\n"
    .string "de temps, rien de\l"
    .string "mieux que les objets.\p"
    .string "Les PROTEINES accroissent l'ATTAQUE\n"
    .string "et le CALCIUM augmente l'ATQ. SPE.$"

LilycoveCity_DepartmentStore_3F_Text_WantMoreEndurance::
    .string "Je veux que mon POKéMON ait plus\n"
    .string "d'endurance.\p"
    .string "Je ne sais pas si je dois élever sa\n"
    .string "DEFENSE avec le FER ou sa\l"
    .string "DEF. SPE. avec le ZINC.$"

LilycoveCity_DepartmentStore_3F_Text_GaveCarbosToSpeedUpMon::
    .string "J'ai donné du CARBONE à mon POKéMON\n"
    .string "et sa VITESSE a augmenté.$"
