LilycoveCity_PokemonCenter_1F_Text_HowManyKindsOfPokemon::
    .string "Je me demande combien de types de\n"
    .string "POKéMON il existe dans le monde.\p"
    .string "Ce serait super de traverser les\n"
    .string "océans et d'échanger des POKéMON\l"
    .string "très loin d'ici.$"

LilycoveCity_PokemonCenter_1F_Text_HaventSeenRottenScoundrels::
    .string "Ces sales vauriens qui volent les\n"
    .string "POKéMON et piquent les METEORITES…\p"
    .string "Je ne les ai pas vus\n"
    .string "dans les parages.$"
