LilycoveCity_ContestLobby_Text_MasterRankHereICome::
    .string "Attention, participants aux CONCOURS\n"
    .string "catégorie MASTER, me voilà!\p"
    .string "Le monde entier va enfin savoir\n"
    .string "que mon cher POKéMON est l'être\l"
    .string "le plus gracieux qui puisse\l"
    .string "exister. Le moment est venu!\p"
    .string "Hé, hé, hé.$"

LilycoveCity_ContestLobby_Text_WholeVarietyOfPokemonHere::
    .string "Il y a une grande variété de\n"
    .string "POKéMON, ici.\p"
    .string "C'est pourquoi je viens tous les\n"
    .string "jours, lors de ma promenade.$"

LilycoveCity_ContestLobby_Text_ContestFeastForEyes::
    .string "Venir voir un CONCOURS est un\n"
    .string "festival pour les yeux!\p"
    .string "On voit plein de superbes POKéMON\n"
    .string "qui crient pour qu'on les peigne.$"

LilycoveCity_ContestLobby_Text_ToughContestIsExtreme::
    .string "Le CONCOURS DE ROBUSTESSE,\n"
    .string "c'est quelque chose, tu sais!\p"
    .string "Cet étalage de muscles… Toute cette\n"
    .string "sueur… Simplement magnifique!$"

LilycoveCity_ContestLobby_Text_LavishedCareOnMon::
    .string "Jour après jour, j'ai prodigué mes\n"
    .string "soins à ce POKéMON.\p"
    .string "Il approche de la perfection.\n"
    .string "Aujourd'hui, la victoire est à moi!$"

LilycoveCity_ContestLobby_Text_MadePokeblocksWithFamily::
    .string "J'ai fait des POKéBLOCS avec\n"
    .string "ma maman, mon papa et ma\l"
    .string "grande sœur. Ils sont super!\p"
    .string "Si tu fais des POKéBLOCS avec\n"
    .string "d'autres personnes, ils sont meilleurs.$"

LilycoveCity_ContestLobby_Text_LadyGaveMePokeblockCase::
    .string "Youpi!\p"
    .string "La femme à la réception vient de\n"
    .string "me donner une boîte pour POKéBLOCS!$"

BerryBlender_Text_LoveMakingPokeblocks::
    .string "J'aime bien faire des POKéBLOCS.\p"
    .string "J'ai toujours quelques BAIES sur moi.$"

BerryBlender_Text_DontHaveAnyBerriesHaveOne::
    .string "Oh?\n"
    .string "Tu n'as pas de BAIES?\p"
    .string "Bon, ça n'fait rien\n"
    .string "pour l'instant, hein?\p"
    .string "Si tu t'en fiches d'avoir les restes,\n"
    .string "tu peux prendre une de mes BAIES.$"

BerryBlender_Text_UseItToMakePokeblocksTogether::
    .string "On va s'en servir pour faire des\n"
    .string "POKéBLOCS ensemble avec le MIXEUR.$"

BerryBlender_Text_MakePokeblocksUsingBerryBlender::
    .string "Si ça te dit, on peut faire quelques\n"
    .string "POKéBLOCS ensemble\l"
    .string "à l'aide du MIXEUR.$"

BerryBlender_Text_DontHaveAnyBerriesNoneToSpare::
    .string "Oh?\n"
    .string "Tu n'as pas de BAIES?\p"
    .string "S'il m'en restait, je t'en donnerais\n"
    .string "une avec grand plaisir…\p"
    .string "Mais je n'en ai aucune en réserve\n"
    .string "aujourd'hui. Désolé.$"
