LilycoveCity_LilycoveMuseum_1F_Text_WelcomeToLilycoveMuseum::
    .string "Bienvenue au MUSEE NENUCRIQUE.\p"
    .string "Prenez le temps d'apprécier notre\n"
    .string "superbe collection sur les POKéMON.$"

LilycoveCity_LilycoveMuseum_1F_Text_MustntForgetLoveForFineArts::
    .string "C'est un plaisir d'affronter les\n"
    .string "POKéMON, je te l'accorde.\p"
    .string "Mais il ne faut pas oublier notre\n"
    .string "amour pour les beaux-arts.$"

LilycoveCity_LilycoveMuseum_1F_Text_ThisMuseumIsInspiration::
    .string "Ce MUSEE D'ART… Eh bien, tu peux y\n"
    .string "voir beaucoup de\l"
    .string "fabuleux tableaux.\p"
    .string "Et le CONSERVATEUR\n"
    .string "est extraordinaire.\p"
    .string "Pour les artistes tels que\n"
    .string "moi, ce MUSEE est une\l"
    .string "véritable source d'inspiration.$"

LilycoveCity_LilycoveMuseum_1F_Text_ThisLadyIsPretty::
    .string "Cette dame est jolie!\n"
    .string "Elle est comme maman!$"

LilycoveCity_LilycoveMuseum_1F_Text_ThisPokemonIsAdorable::
    .string "Ce POKéMON est adorable!\n"
    .string "Tout comme notre petit fiston!$"

LilycoveCity_LilycoveMuseum_1F_Text_VeryOldPainting::
    .string "C'est un tableau très ancien.\n"
    .string "La peinture s'écaille ici et là.$"

LilycoveCity_LilycoveMuseum_1F_Text_OddLandscapeFantasticScenery::
    .string "C'est un curieux paysage avec des\n"
    .string "vues étranges et fantastiques.$"

LilycoveCity_LilycoveMuseum_1F_Text_PaintingOfBeautifulWoman::
    .string "C'est la représentation d'une\n"
    .string "charmante femme avec un POKéMON\l"
    .string "sur ses genoux.$"

LilycoveCity_LilycoveMuseum_1F_Text_PaintingOfLegendaryPokemon::
    .string "C'est la représentation d'un POKéMON\n"
    .string "légendaire de l'ancien temps.\p"
    .string "Il est issu de\n"
    .string "l'imagination du peintre.$"

LilycoveCity_LilycoveMuseum_1F_Text_PaintingOfGrassPokemon::
    .string "C'est la représentation de POKéMON du\n"
    .string "type PLANTE qui vacillent au vent.\p"
    .string "Ils ont l'air d'aimer sentir la caresse\n"
    .string "du vent.$"

LilycoveCity_LilycoveMuseum_1F_Text_PaintingOfBerries::
    .string "C'est une exquise représentation\n"
    .string "de BAIES.\p"
    .string "Ce tableau vous donnerait faim!$"

LilycoveCity_LilycoveMuseum_Text_BirdPokemonSculptureReplica::
    .string "C'est une réplique de\n"
    .string "sculpture connue.\p"
    .string "C'est un antique POKéMON OISEAU.$"

LilycoveCity_LilycoveMuseum_1F_Text_BigPokeBallCarvedFromStone::
    .string "C'est une grosse POKé BALL sculptée\n"
    .string "dans une pierre noire.\p"
    .string "Elle était apparemment utilisée jadis,\n"
    .string "lors de festivals.$"

LilycoveCity_LilycoveMuseum_1F_Text_StoneTabletWithAncientText::
    .string "C'est une immense plaque en pierre. \n"
    .string "Des POKéMON et un texte compact,\l"
    .string "écrit dans une langue ancienne\l"
    .string "indéchiffrable, sont gravés dessus.$"
