@ Adapted (RFVF+): Emerald's ferry LE MARINA, built at the POIVRESSEL shipyard -> the SEAGALLOP ferry to CARMIN SUR MER
LilycoveCity_Harbor_Text_SailorFerryAvailable::
    .string "La FLECHE DES MERS fait enfin\n"
    .string "escale à NENUCRIQUE.\p"
    .string "On peut rejoindre CARMIN SUR MER,\n"
    .string "à KANTO, en un rien de temps!\p"
    .string "Maintenant, à mon tour de bosser!$"

LilycoveCity_Harbor_Text_MayISeeYourTicket::
    .string "Bonjour. C'est pour le ferry?\n"
    .string "Puis-je voir votre PASSE BATEAU?$"

LilycoveCity_Harbor_Text_FlashTicketWhereTo::
    .string "{PLAYER} montre le PASSE BATEAU…\p"
    .string "Parfait! Tout y est!\p"
    .string "Et où souhaitez-vous aller?$"

LilycoveCity_Harbor_Text_PleaseBoard::
    .string "Veuillez monter sur le ferry et\n"
    .string "attendre le départ.$"

LilycoveCity_Harbor_Text_SailAnotherTime::
    .string "Revenez une autre fois!$"
