LilycoveCity_CoveLilyMotel_1F_Text_HouseSittingMonCaughtBurglar::
    .string "Etonnant! Un POKéMON de garde a\n"
    .string "attrapé un voleur?\p"
    .string "Ça alors! Si on avait un POKéMON\n"
    .string "aussi robuste pour monter la garde…\p"
    .string "On aimerait pouvoir garantir une\n"
    .string "totale sécurité à notre clientèle.$"

LilycoveCity_CoveLilyMotel_1F_Text_BetterGetWorkingOnGuestsDinner::
    .string "Oh, pardon! Désolé!\n"
    .string "J'étais absorbé par la télé!\p"
    .string "Oh, oui. Un grand groupe de clients\n"
    .string "est arrivé il y a peu.\p"
    .string "Ils ont réservé sous le nom de GAME\n"
    .string "FREAK. Je suppose\l"
    .string "qu'ils font des jeux.\p"
    .string "Oh, je ferais mieux de m'occuper\n"
    .string "de leur dîner!$"

LilycoveCity_CoveLilyMotel_1F_Text_CantSeeTheTV::
    .string "Hé, faut pas rester là!\n"
    .string "J'vois pas la télé!$"
