LilycoveCity_DepartmentStore_4F_Text_AttackOrDefenseTM::
    .string "Humm…\p"
    .string "Une capacité offensive…\n"
    .string "Une capacité défensive…\p"
    .string "Ce n'est pas facile de savoir quelle\n"
    .string "CT doit apprendre un POKéMON…$"

LilycoveCity_DepartmentStore_4F_Text_FiftyDifferentTMs::
    .string "Il y a tellement de CT différentes.\p"
    .string "Une brochure que j'ai lue indiquait\n"
    .string "qu'il y en avait cinquante sortes.$"

LilycoveCity_DepartmentStore_4F_Text_PokemonOnlyHaveFourMoves::
    .string "J'aimerais bien avoir toutes les\n"
    .string "sortes de CT, mais un POKéMON ne\l"
    .string "peut apprendre que quatre capacités.$"
