#include "global.h"
#include "gflib.h"
#include "constants/event_objects.h"

static EWRAM_DATA const u8 *sStringPointers[8] = {0};

#define COLORS(a, b)((a) | (b << 4))

static const u8 sTextColorTable[] =
{
 // [LOW_NYBBLE / 2]                            = 0xXY, // HIGH_NYBBLE
    [OBJ_EVENT_GFX_RED_NORMAL / 2]              = COLORS(NPC_TEXT_COLOR_MALE, NPC_TEXT_COLOR_MALE), // OBJ_EVENT_GFX_RED_BIKE
    [OBJ_EVENT_GFX_RED_SURF / 2]                = COLORS(NPC_TEXT_COLOR_MALE, NPC_TEXT_COLOR_MALE), // OBJ_EVENT_GFX_RED_FIELD_MOVE
    [OBJ_EVENT_GFX_RED_FISH / 2]                = COLORS(NPC_TEXT_COLOR_MALE, NPC_TEXT_COLOR_MALE), // OBJ_EVENT_GFX_RED_VS_SEEKER
    [OBJ_EVENT_GFX_RED_VS_SEEKER_BIKE / 2]      = COLORS(NPC_TEXT_COLOR_MALE, NPC_TEXT_COLOR_FEMALE), // OBJ_EVENT_GFX_GREEN_NORMAL
    [OBJ_EVENT_GFX_GREEN_BIKE / 2]              = COLORS(NPC_TEXT_COLOR_FEMALE, NPC_TEXT_COLOR_FEMALE), // OBJ_EVENT_GFX_GREEN_SURF
    [OBJ_EVENT_GFX_GREEN_FIELD_MOVE / 2]        = COLORS(NPC_TEXT_COLOR_FEMALE, NPC_TEXT_COLOR_FEMALE), // OBJ_EVENT_GFX_GREEN_FISH
    [OBJ_EVENT_GFX_GREEN_VS_SEEKER / 2]         = COLORS(NPC_TEXT_COLOR_FEMALE, NPC_TEXT_COLOR_FEMALE), // OBJ_EVENT_GFX_GREEN_VS_SEEKER_BIKE
    [OBJ_EVENT_GFX_RS_BRENDAN / 2]              = COLORS(NPC_TEXT_COLOR_MALE, NPC_TEXT_COLOR_FEMALE), // OBJ_EVENT_GFX_RS_MAY
    [OBJ_EVENT_GFX_LITTLE_BOY / 2]              = COLORS(NPC_TEXT_COLOR_MALE, NPC_TEXT_COLOR_FEMALE), // OBJ_EVENT_GFX_LITTLE_GIRL
    [OBJ_EVENT_GFX_YOUNGSTER / 2]               = COLORS(NPC_TEXT_COLOR_MALE, NPC_TEXT_COLOR_MALE), // OBJ_EVENT_GFX_BOY
    [OBJ_EVENT_GFX_BUG_CATCHER / 2]             = COLORS(NPC_TEXT_COLOR_MALE, NPC_TEXT_COLOR_MALE), // OBJ_EVENT_GFX_SITTING_BOY
    [OBJ_EVENT_GFX_LASS / 2]                    = COLORS(NPC_TEXT_COLOR_FEMALE, NPC_TEXT_COLOR_FEMALE), // OBJ_EVENT_GFX_WOMAN_1
    [OBJ_EVENT_GFX_BATTLE_GIRL / 2]             = COLORS(NPC_TEXT_COLOR_FEMALE, NPC_TEXT_COLOR_MALE), // OBJ_EVENT_GFX_MAN
    [OBJ_EVENT_GFX_ROCKER / 2]                  = COLORS(NPC_TEXT_COLOR_MALE, NPC_TEXT_COLOR_MALE), // OBJ_EVENT_GFX_FAT_MAN
    [OBJ_EVENT_GFX_WOMAN_2 / 2]                 = COLORS(NPC_TEXT_COLOR_FEMALE, NPC_TEXT_COLOR_FEMALE), // OBJ_EVENT_GFX_BEAUTY
    [OBJ_EVENT_GFX_BALDING_MAN / 2]             = COLORS(NPC_TEXT_COLOR_MALE, NPC_TEXT_COLOR_FEMALE), // OBJ_EVENT_GFX_WOMAN_3
    [OBJ_EVENT_GFX_OLD_MAN_1 / 2]               = COLORS(NPC_TEXT_COLOR_MALE, NPC_TEXT_COLOR_MALE), // OBJ_EVENT_GFX_OLD_MAN_2
    [OBJ_EVENT_GFX_OLD_MAN_LYING_DOWN / 2]      = COLORS(NPC_TEXT_COLOR_MALE, NPC_TEXT_COLOR_FEMALE), // OBJ_EVENT_GFX_OLD_WOMAN
    [OBJ_EVENT_GFX_TUBER_M_WATER / 2]           = COLORS(NPC_TEXT_COLOR_MALE, NPC_TEXT_COLOR_FEMALE), // OBJ_EVENT_GFX_TUBER_F
    [OBJ_EVENT_GFX_TUBER_M_LAND / 2]            = COLORS(NPC_TEXT_COLOR_MALE, NPC_TEXT_COLOR_MALE), // OBJ_EVENT_GFX_CAMPER
    [OBJ_EVENT_GFX_PICNICKER / 2]               = COLORS(NPC_TEXT_COLOR_FEMALE, NPC_TEXT_COLOR_MALE), // OBJ_EVENT_GFX_COOLTRAINER_M
    [OBJ_EVENT_GFX_COOLTRAINER_F / 2]           = COLORS(NPC_TEXT_COLOR_FEMALE, NPC_TEXT_COLOR_MALE), // OBJ_EVENT_GFX_SWIMMER_M_WATER
    [OBJ_EVENT_GFX_SWIMMER_F_WATER / 2]         = COLORS(NPC_TEXT_COLOR_FEMALE, NPC_TEXT_COLOR_MALE), // OBJ_EVENT_GFX_SWIMMER_M_LAND
    [OBJ_EVENT_GFX_SWIMMER_F_LAND / 2]          = COLORS(NPC_TEXT_COLOR_FEMALE, NPC_TEXT_COLOR_MALE), // OBJ_EVENT_GFX_WORKER_M
    [OBJ_EVENT_GFX_WORKER_F / 2]                = COLORS(NPC_TEXT_COLOR_FEMALE, NPC_TEXT_COLOR_MALE), // OBJ_EVENT_GFX_ROCKET_M
    [OBJ_EVENT_GFX_ROCKET_F / 2]                = COLORS(NPC_TEXT_COLOR_FEMALE, NPC_TEXT_COLOR_MALE), // OBJ_EVENT_GFX_GBA_KID
    [OBJ_EVENT_GFX_SUPER_NERD / 2]              = COLORS(NPC_TEXT_COLOR_MALE, NPC_TEXT_COLOR_MALE), // OBJ_EVENT_GFX_BIKER
    [OBJ_EVENT_GFX_BLACKBELT / 2]               = COLORS(NPC_TEXT_COLOR_MALE, NPC_TEXT_COLOR_MALE), // OBJ_EVENT_GFX_SCIENTIST
    [OBJ_EVENT_GFX_HIKER / 2]                   = COLORS(NPC_TEXT_COLOR_MALE, NPC_TEXT_COLOR_MALE), // OBJ_EVENT_GFX_FISHER
    [OBJ_EVENT_GFX_CHANNELER / 2]               = COLORS(NPC_TEXT_COLOR_FEMALE, NPC_TEXT_COLOR_MALE), // OBJ_EVENT_GFX_CHEF
    [OBJ_EVENT_GFX_POLICEMAN / 2]               = COLORS(NPC_TEXT_COLOR_MALE, NPC_TEXT_COLOR_MALE), // OBJ_EVENT_GFX_GENTLEMAN
    [OBJ_EVENT_GFX_SAILOR / 2]                  = COLORS(NPC_TEXT_COLOR_MALE, NPC_TEXT_COLOR_MALE), // OBJ_EVENT_GFX_CAPTAIN
    [OBJ_EVENT_GFX_NURSE / 2]                   = COLORS(NPC_TEXT_COLOR_FEMALE, NPC_TEXT_COLOR_FEMALE), // OBJ_EVENT_GFX_CABLE_CLUB_RECEPTIONIST
    [OBJ_EVENT_GFX_UNION_ROOM_RECEPTIONIST / 2] = COLORS(NPC_TEXT_COLOR_FEMALE, NPC_TEXT_COLOR_MALE), // OBJ_EVENT_GFX_UNUSED_MALE_RECEPTIONIST
    [OBJ_EVENT_GFX_CLERK / 2]                   = COLORS(NPC_TEXT_COLOR_MALE, NPC_TEXT_COLOR_MALE), // OBJ_EVENT_GFX_MG_DELIVERYMAN
    [OBJ_EVENT_GFX_TRAINER_TOWER_DUDE / 2]      = COLORS(NPC_TEXT_COLOR_MALE, NPC_TEXT_COLOR_MALE), // OBJ_EVENT_GFX_PROF_OAK
    [OBJ_EVENT_GFX_BLUE / 2]                    = COLORS(NPC_TEXT_COLOR_MALE, NPC_TEXT_COLOR_MALE), // OBJ_EVENT_GFX_BILL
    [OBJ_EVENT_GFX_LANCE / 2]                   = COLORS(NPC_TEXT_COLOR_MALE, NPC_TEXT_COLOR_FEMALE), // OBJ_EVENT_GFX_AGATHA
    [OBJ_EVENT_GFX_DAISY / 2]                   = COLORS(NPC_TEXT_COLOR_FEMALE, NPC_TEXT_COLOR_FEMALE), // OBJ_EVENT_GFX_LORELEI
    [OBJ_EVENT_GFX_MR_FUJI / 2]                 = COLORS(NPC_TEXT_COLOR_MALE, NPC_TEXT_COLOR_MALE), // OBJ_EVENT_GFX_BRUNO
    [OBJ_EVENT_GFX_BROCK / 2]                   = COLORS(NPC_TEXT_COLOR_MALE, NPC_TEXT_COLOR_FEMALE), // OBJ_EVENT_GFX_MISTY
    [OBJ_EVENT_GFX_LT_SURGE / 2]                = COLORS(NPC_TEXT_COLOR_MALE, NPC_TEXT_COLOR_FEMALE), // OBJ_EVENT_GFX_ERIKA
    [OBJ_EVENT_GFX_KOGA / 2]                    = COLORS(NPC_TEXT_COLOR_MALE, NPC_TEXT_COLOR_FEMALE), // OBJ_EVENT_GFX_SABRINA
    [OBJ_EVENT_GFX_BLAINE / 2]                  = COLORS(NPC_TEXT_COLOR_MALE, NPC_TEXT_COLOR_MALE), // OBJ_EVENT_GFX_GIOVANNI
    [OBJ_EVENT_GFX_MOM / 2]                     = COLORS(NPC_TEXT_COLOR_FEMALE, NPC_TEXT_COLOR_MALE), // OBJ_EVENT_GFX_CELIO
    [OBJ_EVENT_GFX_TEACHY_TV_HOST / 2]          = COLORS(NPC_TEXT_COLOR_MALE, NPC_TEXT_COLOR_MALE), // OBJ_EVENT_GFX_GYM_GUY
    [OBJ_EVENT_GFX_ITEM_BALL / 2]               = COLORS(NPC_TEXT_COLOR_NEUTRAL, NPC_TEXT_COLOR_NEUTRAL), // OBJ_EVENT_GFX_TOWN_MAP
    [OBJ_EVENT_GFX_POKEDEX / 2]                 = COLORS(NPC_TEXT_COLOR_NEUTRAL, NPC_TEXT_COLOR_NEUTRAL), // OBJ_EVENT_GFX_CUT_TREE
    [OBJ_EVENT_GFX_ROCK_SMASH_ROCK / 2]         = COLORS(NPC_TEXT_COLOR_NEUTRAL, NPC_TEXT_COLOR_NEUTRAL), // OBJ_EVENT_GFX_PUSHABLE_BOULDER
    [OBJ_EVENT_GFX_FOSSIL / 2]                  = COLORS(NPC_TEXT_COLOR_NEUTRAL, NPC_TEXT_COLOR_NEUTRAL), // OBJ_EVENT_GFX_RUBY
    [OBJ_EVENT_GFX_SAPPHIRE / 2]                = COLORS(NPC_TEXT_COLOR_NEUTRAL, NPC_TEXT_COLOR_NEUTRAL), // OBJ_EVENT_GFX_OLD_AMBER
    [OBJ_EVENT_GFX_GYM_SIGN / 2]                = COLORS(NPC_TEXT_COLOR_NEUTRAL, NPC_TEXT_COLOR_NEUTRAL), // OBJ_EVENT_GFX_SIGN
    [OBJ_EVENT_GFX_TRAINER_TIPS / 2]            = COLORS(NPC_TEXT_COLOR_NEUTRAL, NPC_TEXT_COLOR_NEUTRAL), // OBJ_EVENT_GFX_CLIPBOARD
    [OBJ_EVENT_GFX_METEORITE / 2]               = COLORS(NPC_TEXT_COLOR_NEUTRAL, NPC_TEXT_COLOR_NEUTRAL), // OBJ_EVENT_GFX_LAPRAS_DOLL
    [OBJ_EVENT_GFX_SEAGALLOP / 2]               = COLORS(NPC_TEXT_COLOR_NEUTRAL, NPC_TEXT_COLOR_MON), // OBJ_EVENT_GFX_SNORLAX
    [OBJ_EVENT_GFX_SPEAROW / 2]                 = COLORS(NPC_TEXT_COLOR_MON, NPC_TEXT_COLOR_MON), // OBJ_EVENT_GFX_CUBONE
    [OBJ_EVENT_GFX_POLIWRATH / 2]               = COLORS(NPC_TEXT_COLOR_MON, NPC_TEXT_COLOR_MON), // OBJ_EVENT_GFX_CLEFAIRY
    [OBJ_EVENT_GFX_PIDGEOT / 2]                 = COLORS(NPC_TEXT_COLOR_MON, NPC_TEXT_COLOR_MON), // OBJ_EVENT_GFX_JIGGLYPUFF
    [OBJ_EVENT_GFX_PIDGEY / 2]                  = COLORS(NPC_TEXT_COLOR_MON, NPC_TEXT_COLOR_MON), // OBJ_EVENT_GFX_CHANSEY
    [OBJ_EVENT_GFX_OMANYTE / 2]                 = COLORS(NPC_TEXT_COLOR_MON, NPC_TEXT_COLOR_MON), // OBJ_EVENT_GFX_KANGASKHAN
    [OBJ_EVENT_GFX_PIKACHU / 2]                 = COLORS(NPC_TEXT_COLOR_MON, NPC_TEXT_COLOR_MON), // OBJ_EVENT_GFX_PSYDUCK
    [OBJ_EVENT_GFX_NIDORAN_F / 2]               = COLORS(NPC_TEXT_COLOR_MON, NPC_TEXT_COLOR_MON), // OBJ_EVENT_GFX_NIDORAN_M
    [OBJ_EVENT_GFX_NIDORINO / 2]                = COLORS(NPC_TEXT_COLOR_MON, NPC_TEXT_COLOR_MON), // OBJ_EVENT_GFX_MEOWTH
    [OBJ_EVENT_GFX_SEEL / 2]                    = COLORS(NPC_TEXT_COLOR_MON, NPC_TEXT_COLOR_MON), // OBJ_EVENT_GFX_VOLTORB
    [OBJ_EVENT_GFX_SLOWPOKE / 2]                = COLORS(NPC_TEXT_COLOR_MON, NPC_TEXT_COLOR_MON), // OBJ_EVENT_GFX_SLOWBRO
    [OBJ_EVENT_GFX_MACHOP / 2]                  = COLORS(NPC_TEXT_COLOR_MON, NPC_TEXT_COLOR_MON), // OBJ_EVENT_GFX_WIGGLYTUFF
    [OBJ_EVENT_GFX_DODUO / 2]                   = COLORS(NPC_TEXT_COLOR_MON, NPC_TEXT_COLOR_MON), // OBJ_EVENT_GFX_FEAROW
    [OBJ_EVENT_GFX_MACHOKE / 2]                 = COLORS(NPC_TEXT_COLOR_MON, NPC_TEXT_COLOR_MON), // OBJ_EVENT_GFX_LAPRAS
    [OBJ_EVENT_GFX_ZAPDOS / 2]                  = COLORS(NPC_TEXT_COLOR_MON, NPC_TEXT_COLOR_MON), // OBJ_EVENT_GFX_MOLTRES
    [OBJ_EVENT_GFX_ARTICUNO / 2]                = COLORS(NPC_TEXT_COLOR_MON, NPC_TEXT_COLOR_MON), // OBJ_EVENT_GFX_MEWTWO
    [OBJ_EVENT_GFX_MEW / 2]                     = COLORS(NPC_TEXT_COLOR_MON, NPC_TEXT_COLOR_MON), // OBJ_EVENT_GFX_ENTEI
    [OBJ_EVENT_GFX_SUICUNE / 2]                 = COLORS(NPC_TEXT_COLOR_MON, NPC_TEXT_COLOR_MON), // OBJ_EVENT_GFX_RAIKOU
    [OBJ_EVENT_GFX_LUGIA / 2]                   = COLORS(NPC_TEXT_COLOR_MON, NPC_TEXT_COLOR_MON), // OBJ_EVENT_GFX_HO_OH
    [OBJ_EVENT_GFX_CELEBI / 2]                  = COLORS(NPC_TEXT_COLOR_MON, NPC_TEXT_COLOR_MON), // OBJ_EVENT_GFX_KABUTO
    [OBJ_EVENT_GFX_DEOXYS_D / 2]                = COLORS(NPC_TEXT_COLOR_MON, NPC_TEXT_COLOR_MON), // OBJ_EVENT_GFX_DEOXYS_A
    [OBJ_EVENT_GFX_DEOXYS_N / 2]                = COLORS(NPC_TEXT_COLOR_MON, NPC_TEXT_COLOR_NEUTRAL), // OBJ_EVENT_GFX_SS_ANNE
    [OBJ_EVENT_GFX_CUE_BALL / 2]                = COLORS(NPC_TEXT_COLOR_MALE, NPC_TEXT_COLOR_FEMALE), // OBJ_EVENT_GFX_PAINTER
    [OBJ_EVENT_GFX_BIRD_KEEPER / 2]             = COLORS(NPC_TEXT_COLOR_MALE, NPC_TEXT_COLOR_MALE), // OBJ_EVENT_GFX_BURGLAR
    [OBJ_EVENT_GFX_POKEMON_RANGER_F / 2]        = COLORS(NPC_TEXT_COLOR_FEMALE, NPC_TEXT_COLOR_MALE), // OBJ_EVENT_GFX_POKEMON_RANGER_M
    [OBJ_EVENT_GFX_RUIN_MANIAC / 2]             = COLORS(NPC_TEXT_COLOR_MALE, NPC_TEXT_COLOR_MALE), // OBJ_EVENT_GFX_POKE_MANIAC
    [OBJ_EVENT_GFX_PSYCHIC_M / 2]               = COLORS(NPC_TEXT_COLOR_MALE, NPC_TEXT_COLOR_FEMALE), // OBJ_EVENT_GFX_PSYCHIC_F
    [OBJ_EVENT_GFX_AROMA_LADY / 2]              = COLORS(NPC_TEXT_COLOR_FEMALE, NPC_TEXT_COLOR_FEMALE), // OBJ_EVENT_GFX_TWIN
    [OBJ_EVENT_GFX_YOUNG_COUPLE_M / 2]          = COLORS(NPC_TEXT_COLOR_MALE, NPC_TEXT_COLOR_FEMALE), // OBJ_EVENT_GFX_YOUNG_COUPLE_F
    [OBJ_EVENT_GFX_ENGINEER / 2]                = COLORS(NPC_TEXT_COLOR_MALE, NPC_TEXT_COLOR_MALE), // OBJ_EVENT_GFX_JUGGLER
    [OBJ_EVENT_GFX_TAMER / 2]                   = COLORS(NPC_TEXT_COLOR_MALE, NPC_TEXT_COLOR_FEMALE), // OBJ_EVENT_GFX_POKEMON_BREEDER
    [OBJ_EVENT_GFX_RED_UNDERWATER / 2]          = COLORS(NPC_TEXT_COLOR_MALE, NPC_TEXT_COLOR_FEMALE), // OBJ_EVENT_GFX_GREEN_UNDERWATER
    [OBJ_EVENT_GFX_SCOTT / 2]                   = COLORS(NPC_TEXT_COLOR_MALE, NPC_TEXT_COLOR_MON), // OBJ_EVENT_GFX_BULBASAUR
    [OBJ_EVENT_GFX_CHARMANDER / 2]              = COLORS(NPC_TEXT_COLOR_MON, NPC_TEXT_COLOR_MON), // OBJ_EVENT_GFX_SQUIRTLE
    [OBJ_EVENT_GFX_LATIAS / 2]                  = COLORS(NPC_TEXT_COLOR_MON, NPC_TEXT_COLOR_MON), // OBJ_EVENT_GFX_LATIOS
    [OBJ_EVENT_GFX_EM_BRENDAN /2]               = COLORS(NPC_TEXT_COLOR_MALE, NPC_TEXT_COLOR_FEMALE), // OBJ_EVEN_GFX_EM_MAY
    [OBJ_EVENT_GFX_CABLE_CAR /2]                = COLORS(NPC_TEXT_COLOR_NEUTRAL, NPC_TEXT_COLOR_MON), // OBJ_EVEN_GFX_SUDOWOODO
    [OBJ_EVENT_GFX_ABRA /2]                     = COLORS(NPC_TEXT_COLOR_MON, NPC_TEXT_COLOR_FEMALE), // OBJ_EVENT_GFX_SWIMMER_F_WATER_2
    [OBJ_EVENT_GFX_MASTER_BEAUTY / 2]           = COLORS(NPC_TEXT_COLOR_FEMALE, NPC_TEXT_COLOR_MALE), // OBJ_EVENT_GFX_MASTER_BIRD_KEEPER
    [OBJ_EVENT_GFX_MASTER_BLACK_BELT / 2]       = COLORS(NPC_TEXT_COLOR_MALE, NPC_TEXT_COLOR_MALE), // OBJ_EVENT_GFX_MASTER_BUG_CATCHER
    [OBJ_EVENT_GFX_MASTER_COOLTRAINER_M / 2]    = COLORS(NPC_TEXT_COLOR_MALE, NPC_TEXT_COLOR_MALE), // OBJ_EVENT_GFX_MASTER_HIKER
    [OBJ_EVENT_GFX_MASTER_LASS / 2]             = COLORS(NPC_TEXT_COLOR_FEMALE, NPC_TEXT_COLOR_MALE), // OBJ_EVENT_GFX_MASTER_PSYCHIC_M
    [OBJ_EVENT_GFX_MASTER_SCIENTIST / 2]        = COLORS(NPC_TEXT_COLOR_MALE, NPC_TEXT_COLOR_MALE), // OBJ_EVENT_GFX_MASTER_YOUNGSTER
    [OBJ_EVENT_GFX_LADY / 2]                    = COLORS(NPC_TEXT_COLOR_FEMALE, NPC_TEXT_COLOR_MALE), // OBJ_EVENT_GFX_ROCKER_2
    [OBJ_EVENT_GFX_ANABEL / 2]                  = COLORS(NPC_TEXT_COLOR_FEMALE, NPC_TEXT_COLOR_MALE), // OBJ_EVENT_GFX_TUCKER
    [OBJ_EVENT_GFX_GRETA / 2]                   = COLORS(NPC_TEXT_COLOR_FEMALE, NPC_TEXT_COLOR_MALE), // OBJ_EVENT_GFX_SPENSER
    [OBJ_EVENT_GFX_NOLAND / 2]                  = COLORS(NPC_TEXT_COLOR_MALE, NPC_TEXT_COLOR_FEMALE), // OBJ_EVENT_GFX_LUCY
    [OBJ_EVENT_GFX_BRANDON / 2]                 = COLORS(NPC_TEXT_COLOR_MALE, NPC_TEXT_COLOR_MON), // 203
    // 203-208: reserved in event_objects.h for branch dev-regi's Pokemon (MON prints like NEUTRAL, the color past the table)
    [(OBJ_EVENT_GFX_BRANDON + 2) / 2]           = COLORS(NPC_TEXT_COLOR_MON, NPC_TEXT_COLOR_MON), // 205
    [(OBJ_EVENT_GFX_BRANDON + 4) / 2]           = COLORS(NPC_TEXT_COLOR_MON, NPC_TEXT_COLOR_MON), // 207
    [(OBJ_EVENT_GFX_BRANDON + 6) / 2]           = COLORS(NPC_TEXT_COLOR_MON, NPC_TEXT_COLOR_NEUTRAL), // 209: free
    // 210-255: free Kanto ids and OBJ_EVENT_GFX_VAR_x: NEUTRAL, like any id past the table
    [(OBJ_EVENT_GFX_BRANDON + 8) / 2 ... HOENN_OBJ_EVENT_GFX_BASE / 2 - 1] = COLORS(NPC_TEXT_COLOR_NEUTRAL, NPC_TEXT_COLOR_NEUTRAL),
    // BEGIN generated by tools/hoenn_import/hoenn_sprites.py: text colors
    [OBJ_EVENT_GFX_HOENN_NINJA_BOY / 2]         = COLORS(NPC_TEXT_COLOR_MALE, NPC_TEXT_COLOR_MALE), // OBJ_EVENT_GFX_HOENN_BOY_1
    [OBJ_EVENT_GFX_HOENN_GIRL_1 / 2]            = COLORS(NPC_TEXT_COLOR_FEMALE, NPC_TEXT_COLOR_MALE), // OBJ_EVENT_GFX_HOENN_BOY_2
    [OBJ_EVENT_GFX_HOENN_GIRL_2 / 2]            = COLORS(NPC_TEXT_COLOR_FEMALE, NPC_TEXT_COLOR_MALE), // OBJ_EVENT_GFX_HOENN_BOY_3
    [OBJ_EVENT_GFX_HOENN_GIRL_3 / 2]            = COLORS(NPC_TEXT_COLOR_FEMALE, NPC_TEXT_COLOR_MALE), // OBJ_EVENT_GFX_HOENN_RICH_BOY
    [OBJ_EVENT_GFX_HOENN_POKEFAN_F / 2]         = COLORS(NPC_TEXT_COLOR_FEMALE, NPC_TEXT_COLOR_MALE), // OBJ_EVENT_GFX_HOENN_MAN_1
    [OBJ_EVENT_GFX_HOENN_EXPERT_M / 2]          = COLORS(NPC_TEXT_COLOR_MALE, NPC_TEXT_COLOR_FEMALE), // OBJ_EVENT_GFX_HOENN_EXPERT_F
    [OBJ_EVENT_GFX_HOENN_MAN_2 / 2]             = COLORS(NPC_TEXT_COLOR_MALE, NPC_TEXT_COLOR_MALE), // OBJ_EVENT_GFX_HOENN_POKEFAN_M
    [OBJ_EVENT_GFX_HOENN_WOMAN_4 / 2]           = COLORS(NPC_TEXT_COLOR_FEMALE, NPC_TEXT_COLOR_MALE), // OBJ_EVENT_GFX_HOENN_MAN_3
    [OBJ_EVENT_GFX_HOENN_WOMAN_5 / 2]           = COLORS(NPC_TEXT_COLOR_FEMALE, NPC_TEXT_COLOR_MALE), // OBJ_EVENT_GFX_HOENN_SCHOOL_KID_M
    [OBJ_EVENT_GFX_HOENN_RUNNING_TRIATHLETE_M / 2] = COLORS(NPC_TEXT_COLOR_MALE, NPC_TEXT_COLOR_MALE), // OBJ_EVENT_GFX_HOENN_MAN_4
    [OBJ_EVENT_GFX_HOENN_CONTEST_JUDGE / 2]     = COLORS(NPC_TEXT_COLOR_MALE, NPC_TEXT_COLOR_MON), // OBJ_EVENT_GFX_HOENN_KECLEON
    [OBJ_EVENT_GFX_HOENN_AZUMARILL / 2]         = COLORS(NPC_TEXT_COLOR_MON, NPC_TEXT_COLOR_MALE), // OBJ_EVENT_GFX_HOENN_ARTIST
    [OBJ_EVENT_GFX_HOENN_QUINTY_PLUMP / 2]      = COLORS(NPC_TEXT_COLOR_MALE, NPC_TEXT_COLOR_FEMALE), // OBJ_EVENT_GFX_HOENN_TWIN
    [OBJ_EVENT_GFX_HOENN_LITTLE_BOY / 2]        = COLORS(NPC_TEXT_COLOR_MALE, NPC_TEXT_COLOR_FEMALE), // OBJ_EVENT_GFX_HOENN_LITTLE_GIRL
    [OBJ_EVENT_GFX_HOENN_WOMAN_1 / 2]           = COLORS(NPC_TEXT_COLOR_FEMALE, NPC_TEXT_COLOR_MALE), // OBJ_EVENT_GFX_HOENN_FAT_MAN
    [OBJ_EVENT_GFX_HOENN_WOMAN_2 / 2]           = COLORS(NPC_TEXT_COLOR_FEMALE, NPC_TEXT_COLOR_FEMALE), // OBJ_EVENT_GFX_HOENN_WOMAN_3
    [OBJ_EVENT_GFX_HOENN_COOK / 2]              = COLORS(NPC_TEXT_COLOR_MALE, NPC_TEXT_COLOR_FEMALE), // OBJ_EVENT_GFX_HOENN_LINK_RECEPTIONIST
    [OBJ_EVENT_GFX_HOENN_OLD_MAN / 2]           = COLORS(NPC_TEXT_COLOR_MALE, NPC_TEXT_COLOR_FEMALE), // OBJ_EVENT_GFX_HOENN_OLD_WOMAN
    [OBJ_EVENT_GFX_HOENN_CAMPER / 2]            = COLORS(NPC_TEXT_COLOR_MALE, NPC_TEXT_COLOR_FEMALE), // OBJ_EVENT_GFX_HOENN_PICNICKER
    [OBJ_EVENT_GFX_HOENN_YOUNGSTER / 2]         = COLORS(NPC_TEXT_COLOR_MALE, NPC_TEXT_COLOR_MALE), // OBJ_EVENT_GFX_HOENN_BUG_CATCHER
    [OBJ_EVENT_GFX_HOENN_PSYCHIC_M / 2]         = COLORS(NPC_TEXT_COLOR_MALE, NPC_TEXT_COLOR_MALE), // OBJ_EVENT_GFX_HOENN_MANIAC
    [OBJ_EVENT_GFX_HOENN_HEX_MANIAC / 2]        = COLORS(NPC_TEXT_COLOR_FEMALE, NPC_TEXT_COLOR_MON), // OBJ_EVENT_GFX_HOENN_RAYQUAZA_STILL
    [OBJ_EVENT_GFX_HOENN_SWIMMER_M / 2]         = COLORS(NPC_TEXT_COLOR_MALE, NPC_TEXT_COLOR_FEMALE), // OBJ_EVENT_GFX_HOENN_SWIMMER_F
    [OBJ_EVENT_GFX_HOENN_BLACK_BELT / 2]        = COLORS(NPC_TEXT_COLOR_MALE, NPC_TEXT_COLOR_FEMALE), // OBJ_EVENT_GFX_HOENN_BEAUTY
    [OBJ_EVENT_GFX_HOENN_SCIENTIST_1 / 2]       = COLORS(NPC_TEXT_COLOR_MALE, NPC_TEXT_COLOR_FEMALE), // OBJ_EVENT_GFX_HOENN_LASS
    [OBJ_EVENT_GFX_HOENN_GENTLEMAN / 2]         = COLORS(NPC_TEXT_COLOR_MALE, NPC_TEXT_COLOR_MALE), // OBJ_EVENT_GFX_HOENN_SAILOR
    [OBJ_EVENT_GFX_HOENN_FISHERMAN / 2]         = COLORS(NPC_TEXT_COLOR_MALE, NPC_TEXT_COLOR_FEMALE), // OBJ_EVENT_GFX_HOENN_RUNNING_TRIATHLETE_F
    [OBJ_EVENT_GFX_HOENN_TUBER_F / 2]           = COLORS(NPC_TEXT_COLOR_FEMALE, NPC_TEXT_COLOR_MALE), // OBJ_EVENT_GFX_HOENN_TUBER_M
    [OBJ_EVENT_GFX_HOENN_HIKER / 2]             = COLORS(NPC_TEXT_COLOR_MALE, NPC_TEXT_COLOR_MALE), // OBJ_EVENT_GFX_HOENN_CYCLING_TRIATHLETE_M
    [OBJ_EVENT_GFX_HOENN_CYCLING_TRIATHLETE_F / 2] = COLORS(NPC_TEXT_COLOR_FEMALE, NPC_TEXT_COLOR_FEMALE), // OBJ_EVENT_GFX_HOENN_NURSE
    [OBJ_EVENT_GFX_HOENN_ITEM_BALL / 2]         = COLORS(NPC_TEXT_COLOR_NEUTRAL, NPC_TEXT_COLOR_MALE), // OBJ_EVENT_GFX_HOENN_PROF_BIRCH
    [OBJ_EVENT_GFX_HOENN_MAN_5 / 2]             = COLORS(NPC_TEXT_COLOR_MALE, NPC_TEXT_COLOR_MALE), // OBJ_EVENT_GFX_HOENN_REPORTER_M
    [OBJ_EVENT_GFX_HOENN_REPORTER_F / 2]        = COLORS(NPC_TEXT_COLOR_FEMALE, NPC_TEXT_COLOR_MALE), // OBJ_EVENT_GFX_HOENN_BARD
    [OBJ_EVENT_GFX_HOENN_ANABEL / 2]            = COLORS(NPC_TEXT_COLOR_FEMALE, NPC_TEXT_COLOR_MALE), // OBJ_EVENT_GFX_HOENN_TUCKER
    [OBJ_EVENT_GFX_HOENN_GRETA / 2]             = COLORS(NPC_TEXT_COLOR_FEMALE, NPC_TEXT_COLOR_MALE), // OBJ_EVENT_GFX_HOENN_SPENSER
    [OBJ_EVENT_GFX_HOENN_NOLAND / 2]            = COLORS(NPC_TEXT_COLOR_MALE, NPC_TEXT_COLOR_FEMALE), // OBJ_EVENT_GFX_HOENN_LUCY
    [OBJ_EVENT_GFX_HOENN_CUTTABLE_TREE / 2]     = COLORS(NPC_TEXT_COLOR_NEUTRAL, NPC_TEXT_COLOR_MALE), // OBJ_EVENT_GFX_HOENN_MART_EMPLOYEE
    [OBJ_EVENT_GFX_HOENN_ROOFTOP_SALE_WOMAN / 2] = COLORS(NPC_TEXT_COLOR_FEMALE, NPC_TEXT_COLOR_FEMALE), // OBJ_EVENT_GFX_HOENN_TEALA
    [OBJ_EVENT_GFX_HOENN_BREAKABLE_ROCK / 2]    = COLORS(NPC_TEXT_COLOR_NEUTRAL, NPC_TEXT_COLOR_NEUTRAL), // OBJ_EVENT_GFX_HOENN_PUSHABLE_BOULDER
    [OBJ_EVENT_GFX_HOENN_MR_BRINEYS_BOAT / 2]   = COLORS(NPC_TEXT_COLOR_NEUTRAL, NPC_TEXT_COLOR_NEUTRAL), // OBJ_EVENT_GFX_HOENN_TRUCK
    [OBJ_EVENT_GFX_HOENN_VIGOROTH_CARRYING_BOX / 2] = COLORS(NPC_TEXT_COLOR_MON, NPC_TEXT_COLOR_MON), // OBJ_EVENT_GFX_HOENN_VIGOROTH_FACING_AWAY
    [OBJ_EVENT_GFX_HOENN_BIRCHS_BAG / 2]        = COLORS(NPC_TEXT_COLOR_NEUTRAL, NPC_TEXT_COLOR_MON), // OBJ_EVENT_GFX_HOENN_ZIGZAGOON_1
    [OBJ_EVENT_GFX_HOENN_RIVAL_BRENDAN_NORMAL / 2] = COLORS(NPC_TEXT_COLOR_MALE, NPC_TEXT_COLOR_MALE), // OBJ_EVENT_GFX_HOENN_RIVAL_BRENDAN_MACH_BIKE
    [OBJ_EVENT_GFX_HOENN_RIVAL_BRENDAN_ACRO_BIKE / 2] = COLORS(NPC_TEXT_COLOR_MALE, NPC_TEXT_COLOR_MALE), // OBJ_EVENT_GFX_HOENN_RIVAL_BRENDAN_SURFING
    [OBJ_EVENT_GFX_HOENN_RIVAL_BRENDAN_FIELD_MOVE / 2] = COLORS(NPC_TEXT_COLOR_MALE, NPC_TEXT_COLOR_FEMALE), // OBJ_EVENT_GFX_HOENN_RIVAL_MAY_NORMAL
    [OBJ_EVENT_GFX_HOENN_RIVAL_MAY_MACH_BIKE / 2] = COLORS(NPC_TEXT_COLOR_FEMALE, NPC_TEXT_COLOR_FEMALE), // OBJ_EVENT_GFX_HOENN_RIVAL_MAY_ACRO_BIKE
    [OBJ_EVENT_GFX_HOENN_RIVAL_MAY_SURFING / 2] = COLORS(NPC_TEXT_COLOR_FEMALE, NPC_TEXT_COLOR_FEMALE), // OBJ_EVENT_GFX_HOENN_RIVAL_MAY_FIELD_MOVE
    [OBJ_EVENT_GFX_HOENN_CAMERAMAN / 2]         = COLORS(NPC_TEXT_COLOR_MALE, NPC_TEXT_COLOR_NEUTRAL), // OBJ_EVENT_GFX_HOENN_MOVING_BOX
    [OBJ_EVENT_GFX_HOENN_CABLE_CAR / 2]         = COLORS(NPC_TEXT_COLOR_NEUTRAL, NPC_TEXT_COLOR_MALE), // OBJ_EVENT_GFX_HOENN_SCIENTIST_2
    [OBJ_EVENT_GFX_HOENN_DEVON_EMPLOYEE / 2]    = COLORS(NPC_TEXT_COLOR_MALE, NPC_TEXT_COLOR_MALE), // OBJ_EVENT_GFX_HOENN_AQUA_MEMBER_M
    [OBJ_EVENT_GFX_HOENN_AQUA_MEMBER_F / 2]     = COLORS(NPC_TEXT_COLOR_FEMALE, NPC_TEXT_COLOR_MALE), // OBJ_EVENT_GFX_HOENN_MAGMA_MEMBER_M
    [OBJ_EVENT_GFX_HOENN_MAGMA_MEMBER_F / 2]    = COLORS(NPC_TEXT_COLOR_FEMALE, NPC_TEXT_COLOR_MALE), // OBJ_EVENT_GFX_HOENN_SIDNEY
    [OBJ_EVENT_GFX_HOENN_PHOEBE / 2]            = COLORS(NPC_TEXT_COLOR_FEMALE, NPC_TEXT_COLOR_FEMALE), // OBJ_EVENT_GFX_HOENN_GLACIA
    [OBJ_EVENT_GFX_HOENN_DRAKE / 2]             = COLORS(NPC_TEXT_COLOR_MALE, NPC_TEXT_COLOR_FEMALE), // OBJ_EVENT_GFX_HOENN_ROXANNE
    [OBJ_EVENT_GFX_HOENN_BRAWLY / 2]            = COLORS(NPC_TEXT_COLOR_MALE, NPC_TEXT_COLOR_MALE), // OBJ_EVENT_GFX_HOENN_WATTSON
    [OBJ_EVENT_GFX_HOENN_FLANNERY / 2]          = COLORS(NPC_TEXT_COLOR_FEMALE, NPC_TEXT_COLOR_MALE), // OBJ_EVENT_GFX_HOENN_NORMAN
    [OBJ_EVENT_GFX_HOENN_WINONA / 2]            = COLORS(NPC_TEXT_COLOR_FEMALE, NPC_TEXT_COLOR_FEMALE), // OBJ_EVENT_GFX_HOENN_LIZA
    [OBJ_EVENT_GFX_HOENN_TATE / 2]              = COLORS(NPC_TEXT_COLOR_MALE, NPC_TEXT_COLOR_MALE), // OBJ_EVENT_GFX_HOENN_WALLACE
    [OBJ_EVENT_GFX_HOENN_STEVEN / 2]            = COLORS(NPC_TEXT_COLOR_MALE, NPC_TEXT_COLOR_MALE), // OBJ_EVENT_GFX_HOENN_WALLY
    [OBJ_EVENT_GFX_HOENN_LITTLE_BOY_3 / 2]      = COLORS(NPC_TEXT_COLOR_MALE, NPC_TEXT_COLOR_FEMALE), // OBJ_EVENT_GFX_HOENN_HOT_SPRINGS_OLD_WOMAN
    [OBJ_EVENT_GFX_HOENN_SS_TIDAL / 2]          = COLORS(NPC_TEXT_COLOR_NEUTRAL, NPC_TEXT_COLOR_NEUTRAL), // OBJ_EVENT_GFX_HOENN_SUBMARINE_SHADOW
    [OBJ_EVENT_GFX_HOENN_LATIAS / 2]            = COLORS(NPC_TEXT_COLOR_MON, NPC_TEXT_COLOR_MON), // OBJ_EVENT_GFX_HOENN_LATIOS
    [OBJ_EVENT_GFX_HOENN_GAMEBOY_KID / 2]       = COLORS(NPC_TEXT_COLOR_MALE, NPC_TEXT_COLOR_MALE), // OBJ_EVENT_GFX_HOENN_ARCHIE
    [OBJ_EVENT_GFX_HOENN_MAXIE / 2]             = COLORS(NPC_TEXT_COLOR_MALE, NPC_TEXT_COLOR_MON), // OBJ_EVENT_GFX_HOENN_KYOGRE_FRONT
    [OBJ_EVENT_GFX_HOENN_GROUDON_FRONT / 2]     = COLORS(NPC_TEXT_COLOR_MON, NPC_TEXT_COLOR_NEUTRAL), // OBJ_EVENT_GFX_HOENN_FOSSIL
    [OBJ_EVENT_GFX_HOENN_REGIROCK / 2]          = COLORS(NPC_TEXT_COLOR_MON, NPC_TEXT_COLOR_MON), // OBJ_EVENT_GFX_HOENN_REGICE
    [OBJ_EVENT_GFX_HOENN_REGISTEEL / 2]         = COLORS(NPC_TEXT_COLOR_MON, NPC_TEXT_COLOR_MON), // OBJ_EVENT_GFX_HOENN_SKITTY
    [OBJ_EVENT_GFX_HOENN_KYOGRE_ASLEEP / 2]     = COLORS(NPC_TEXT_COLOR_MON, NPC_TEXT_COLOR_MON), // OBJ_EVENT_GFX_HOENN_GROUDON_ASLEEP
    [OBJ_EVENT_GFX_HOENN_RAYQUAZA / 2]          = COLORS(NPC_TEXT_COLOR_MON, NPC_TEXT_COLOR_MON), // OBJ_EVENT_GFX_HOENN_ZIGZAGOON_2
    [OBJ_EVENT_GFX_HOENN_PIKACHU / 2]           = COLORS(NPC_TEXT_COLOR_MON, NPC_TEXT_COLOR_MON), // OBJ_EVENT_GFX_HOENN_WINGULL
    [OBJ_EVENT_GFX_HOENN_KECLEON_BRIDGE_SHADOW / 2] = COLORS(NPC_TEXT_COLOR_MON, NPC_TEXT_COLOR_MALE), // OBJ_EVENT_GFX_HOENN_TUBER_M_SWIMMING
    [OBJ_EVENT_GFX_HOENN_AZURILL / 2]           = COLORS(NPC_TEXT_COLOR_MON, NPC_TEXT_COLOR_FEMALE), // OBJ_EVENT_GFX_HOENN_MOM
    [OBJ_EVENT_GFX_HOENN_JUAN / 2]              = COLORS(NPC_TEXT_COLOR_MALE, NPC_TEXT_COLOR_MALE), // OBJ_EVENT_GFX_HOENN_SCOTT
    [OBJ_EVENT_GFX_HOENN_POOCHYENA / 2]         = COLORS(NPC_TEXT_COLOR_MON, NPC_TEXT_COLOR_MON), // OBJ_EVENT_GFX_HOENN_KYOGRE_SIDE
    [OBJ_EVENT_GFX_HOENN_GROUDON_SIDE / 2]      = COLORS(NPC_TEXT_COLOR_MON, NPC_TEXT_COLOR_MALE), // OBJ_EVENT_GFX_HOENN_MYSTERY_GIFT_MAN
    [OBJ_EVENT_GFX_HOENN_TRICK_HOUSE_STATUE / 2] = COLORS(NPC_TEXT_COLOR_NEUTRAL, NPC_TEXT_COLOR_MON), // OBJ_EVENT_GFX_HOENN_KIRLIA
    [OBJ_EVENT_GFX_HOENN_DUSCLOPS / 2]          = COLORS(NPC_TEXT_COLOR_MON, NPC_TEXT_COLOR_FEMALE), // OBJ_EVENT_GFX_HOENN_UNION_ROOM_NURSE
    [OBJ_EVENT_GFX_HOENN_SUDOWOODO / 2]         = COLORS(NPC_TEXT_COLOR_MON, NPC_TEXT_COLOR_MON), // OBJ_EVENT_GFX_HOENN_MEW
    [OBJ_EVENT_GFX_HOENN_DEOXYS / 2]            = COLORS(NPC_TEXT_COLOR_MON, NPC_TEXT_COLOR_NEUTRAL), // OBJ_EVENT_GFX_HOENN_DEOXYS_TRIANGLE
    [OBJ_EVENT_GFX_HOENN_BRANDON / 2]           = COLORS(NPC_TEXT_COLOR_MALE, NPC_TEXT_COLOR_MON), // OBJ_EVENT_GFX_HOENN_LUGIA
    [OBJ_EVENT_GFX_HOENN_HOOH / 2]              = COLORS(NPC_TEXT_COLOR_MON, NPC_TEXT_COLOR_NEUTRAL), // 417: none
    // END generated by tools/hoenn_import/hoenn_sprites.py: text colors
};
// One entry per 2 ids. An id without an entry prints NPC_TEXT_COLOR_MALE (0) inside the table and NEUTRAL past its
// end: give every new id a color, and unused ids between region blocks a NEUTRAL range (like 210-255 above).
STATIC_ASSERT(NELEMS(sTextColorTable) == (NUM_OBJ_EVENT_GFX + 1) / 2, TextColorTableCoversAllGfxIds);

void DynamicPlaceholderTextUtil_Reset(void)
{
    const u8 **ptr = sStringPointers;
    u8 *fillval = NULL;
    const u8 **ptr2 = ptr + (NELEMS(sStringPointers) - 1);
    
    do
    {
        *ptr2-- = fillval;
    }
    while ((intptr_t)ptr2 >= (intptr_t)ptr);
}

void DynamicPlaceholderTextUtil_SetPlaceholderPtr(u8 idx, const u8 *ptr)
{
    if (idx < NELEMS(sStringPointers))
        sStringPointers[idx] = ptr;
}

u8 *DynamicPlaceholderTextUtil_ExpandPlaceholders(u8 *dest, const u8 *src)
{
    while (*src != EOS)
    {
        if (*src != CHAR_DYNAMIC)
        {
            *dest++ = *src++;
        }
        else
        {
            src++;
            if (sStringPointers[*src] != NULL)
                dest = StringCopy(dest, sStringPointers[*src]);
            src++;
        }
    }
    *dest = EOS;
    return dest;
}

const u8 *DynamicPlaceholderTextUtil_GetPlaceholderPtr(u8 idx)
{
    return sStringPointers[idx];
}

u8 GetColorFromTextColorTable(u16 graphicId)
{
    u32 test = graphicId >> 1;
    u32 shift = (graphicId & 1) << 2;

    if (test >= NELEMS(sTextColorTable))
        return 3;
    else
        return (sTextColorTable[graphicId >> 1] >> shift) & 0xF;
}
