LilycoveCity_House4_Text_MysteriesAtBottomOfSea::
    .string "Les plus grands mystères de cette\n"
    .string "planète se trouvent\l"
    .string "au fond de l'océan.\p"
    .string "Quelqu'un a dit ça,\n"
    .string "mais j'sais plus qui…$"

LilycoveCity_House4_Text_UnderwaterTrenchMossdeepSootopolis::
    .string "Il y a un abîme tout au\n"
    .string "fond de l'eau, entre\l"
    .string "ALGATIA et ATALANOPOLIS.\p"
    .string "En tout cas, c'est ce qu'on m'a dit.$"
